config/sets/laravel60.php

When `LaravelSetList::LARAVEL_60` applied, the code changes as below:
```diff
-DB::connection($connection)->table($table);
+DB::connection($connection)->table($table, 'null');
```
Expected Behavior:
```diff
-DB::connection($connection)->table($table);
+DB::connection($connection)->table($table, null);
```
Related rectorphp/rector#5997

Stripping quotation marks of argument default value

---

config/sets/laravel70.php
src/Set/LaravelSetList.php

Add set for Laravel 7.x

---

config/sets/laravel80.php
src/Rector/ClassMethod/AddArgumentDefaultValueRector.php
src/Rector/ClassMethod/AddParentRegisterToEventServiceProviderRector.php
src/Rector/MethodCall/RemoveAllOnDispatchingMethodsWithJobChainingRector.php
src/Set/LaravelSetList.php
src/ValueObject/AddArgumentDefaultValue.php
stubs/Illuminate/Contracts/Events/Dispatcher.php
stubs/Illuminate/Foundation/Bus/Dispatchable.php
stubs/Illuminate/Foundation/Bus/PendingChain.php
stubs/Illuminate/Foundation/Support/Providers/EventServiceProvider.php
tests/Rector/ClassMethod/AddArgumentDefaultValueRector/AddArgumentDefaultValueRectorTest.php
tests/Rector/ClassMethod/AddArgumentDefaultValueRector/Fixture/fixture.php.inc
tests/Rector/ClassMethod/AddArgumentDefaultValueRector/Fixture/fixture2.php.inc
tests/Rector/ClassMethod/AddArgumentDefaultValueRector/config/configured_rule.php
tests/Rector/ClassMethod/AddParentRegisterToEventServiceProviderRector/AddParentRegisterToEventServiceProviderRectorTest.php
tests/Rector/ClassMethod/AddParentRegisterToEventServiceProviderRector/Fixture/fixture.php.inc
tests/Rector/ClassMethod/AddParentRegisterToEventServiceProviderRector/Fixture/on_the_last_line.php.inc
tests/Rector/ClassMethod/AddParentRegisterToEventServiceProviderRector/config/configured_rule.php
tests/Rector/MethodCall/RemoveAllOnDispatchingMethodsWithJobChainingRector/Fixture/fixture.php.inc
tests/Rector/MethodCall/RemoveAllOnDispatchingMethodsWithJobChainingRector/RemoveAllOnDispatchingMethodsWithJobChainingRectorTest.php
tests/Rector/MethodCall/RemoveAllOnDispatchingMethodsWithJobChainingRector/Source/ChainJob.php
tests/Rector/MethodCall/RemoveAllOnDispatchingMethodsWithJobChainingRector/Source/Job.php
tests/Rector/MethodCall/RemoveAllOnDispatchingMethodsWithJobChainingRector/config/configured_rule.php

Add set for Laravel 8.x

---

src/Rector/Assign/CallOnAppArrayAccessToStandaloneAssignRector.php
src/Rector/MethodCall/ChangeQueryWhereDateValueWithCarbonRector.php
src/Rector/New_/AddGuardToLoginEventRector.php

Based on https://github.com/rectorphp/rector-src/pull/812 as this direct call is deprecated.

[PostRector] Using NodesToAddCollector on rector rules

---

src/NodeFactory/RouterRegisterNodeAnalyzer.php
src/Rector/StaticCall/RouteActionCallableRector.php
stubs/Illuminate/Support/Facades/Route.php
tests/Rector/StaticCall/RouteActionCallableRector/Fixture/fixture.php.inc
tests/Rector/StaticCall/RouteActionCallableRector/Fixture/skip_method_not_exists.php.inc
tests/Rector/StaticCall/RouteActionCallableRector/Fixture/skip_multiple_at.php.inc
tests/Rector/StaticCall/RouteActionCallableRector/RouteActionCallableRectorTest.php
tests/Rector/StaticCall/RouteActionCallableRector/Source/SomeController.php
tests/Rector/StaticCall/RouteActionCallableRector/config/configured_rule.php

Use PHP callable syntax instead of string syntax for controller route declarations, which provides better support for jumping to the controller class in many IDEs.
```diff
use Illuminate\Support\Facades\Route;
-Route::get('/users', 'App\Http\Controllers\UserController@index');
+Route::get('/users', [\App\Http\Controllers\UserController::class, 'index']);
```

Add RouteActionCallableRector

---

config/sets/laravel57.php
config/sets/laravel80.php
src/Rector/Class_/UnifyModelDatesWithCastsRector.php
tests/Rector/Class_/UnifyModelDatesWithCastsRector/Fixture/casts_property_not_exists.php.inc
tests/Rector/Class_/UnifyModelDatesWithCastsRector/Fixture/dates_exists_in_casts.php.inc
tests/Rector/Class_/UnifyModelDatesWithCastsRector/Fixture/fixture.php.inc
tests/Rector/Class_/UnifyModelDatesWithCastsRector/UnifyModelDatesWithCastsRectorTest.php
tests/Rector/Class_/UnifyModelDatesWithCastsRector/config/configured_rule.php

Ref: https://github.com/laravel/framework/pull/32856
Unifying `$dates` with `$casts` will remove ambiguity and give developers a single place for casting their _date_ attributes as well as other attributes. 
**Before**
```php
class Person extends Model
{
protected $casts = [
'age' => 'integer',
];
protected $dates = ['birthday'];
}
```
**After**
```php
class Person extends Model
{
protected $casts = [
'age' => 'integer',
'birthday' => 'datetime',
];
}
```

Add UnifyModelDatesWithCastsRector

---

docs/rector_rules_overview.md
src/Rector/Class_/AnonymousMigrationsRector.php
stubs/Illuminate/Database/Migrations/Migration.php
tests/Rector/Class_/AnonymousMigrationsRector/AnonymousMigrationsRectorTest.php
tests/Rector/Class_/AnonymousMigrationsRector/Fixture/fixture.php.inc
tests/Rector/Class_/AnonymousMigrationsRector/Fixture/skip_anonymous_migration.php.inc
tests/Rector/Class_/AnonymousMigrationsRector/config/configured_rule.php

Convert migrations to anonymous classes to prevent duplication of class names. 
Ref: https://github.com/laravel/framework/pull/36906, https://github.com/laravel/framework/pull/37352
```diff
use Illuminate\Database\Migrations\Migration;
-class CreateUsersTable extends Migration
+return new class extends Migration
{
// ...
-}
+};
```

Add AnonymousMigrationsRector

---

config/sets/laravel54.php

Ref: https://github.com/laravel/framework/commit/f23ac640fa403ca8d4131c36367b53e123b6b852

Added renaming of database assertions not listed in the 5.4 Upgrade Guide

---

src/Rector/PropertyFetch/OptionalToNullsafeOperatorRector.php

ref https://github.com/rectorphp/rector-src/pull/1422, this Rule is executed, even the `excludeMethods` config not configured.

[Laravel] Set implements AllowEmptyConfigurableRectorInterface on OptionalToNullsafeOperatorRector

---

composer.json
docs/rector_rules_overview.md
src/Rector/ClassMethod/AddGenericReturnTypeToRelationsRector.php
stubs/Illuminate/Database/Eloquent/Relations/HasMany.php
stubs/Illuminate/Database/Eloquent/Relations/Relation.php
tests/Rector/ClassMethod/AddGenericReturnTypeToRelationsRector/AddGenericReturnTypeToRelationsRectorTest.php
tests/Rector/ClassMethod/AddGenericReturnTypeToRelationsRector/Fixture/empty-phpdoc.php.inc
tests/Rector/ClassMethod/AddGenericReturnTypeToRelationsRector/Fixture/no-phpdoc.php.inc
tests/Rector/ClassMethod/AddGenericReturnTypeToRelationsRector/Fixture/phpdoc-with-existing-return.php.inc
tests/Rector/ClassMethod/AddGenericReturnTypeToRelationsRector/Fixture/phpdoc-without-return.php.inc
tests/Rector/ClassMethod/AddGenericReturnTypeToRelationsRector/Fixture/relation-in-trait.php.inc
tests/Rector/ClassMethod/AddGenericReturnTypeToRelationsRector/Fixture/relation-without-return-type.php.inc
tests/Rector/ClassMethod/AddGenericReturnTypeToRelationsRector/config/configured_rule.php

This PR adds a new rector called `AddGenericReturnTypeToRelationsRector` Which adds generic return type docblocks to Laravel relations in models.
Laravel relations are not generic. But Larastan (PHPStan extension for Laravel) makes them generic to be able to do more accurate analysis on relations. So this rector is not really useful for normal Laravel users, but only for Larastan users. I hope you'll still accept it though.
I tried to implement it in a way that it will add `@return` doc tag if
- the method has a relation return type (There are other rectors to add missing return types)
- the method doesn't have any comments at all
- the method has comments but no existing `@return`
- the method only has 1 statement in body and it's `return` keyword. (this is how almost all Laravel …

Add AddGenericReturnTypeToRelationsRector

---

config/config.php

To avoid error like:
```
[ERROR] Expected an instance of this class or to this class among his parents                                          
Rector\Core\Contract\Rector\RectorInterface. Got: string in                                                    
/Users/samsonasik/www/rector-symfony/config/config.php (which is being imported from                           
"/Users/samsonasik/www/rector-symfony/rector.php").      
```

Revert RectorConfig->rule usage on config/config

---

docs/rector_rules_overview.md
src/Rector/MethodCall/RedirectRouteToToRouteHelperRector.php
tests/Rector/MethodCall/RedirectRouteToToRouteHelperRector/Fixture/fixture.php.inc
tests/Rector/MethodCall/RedirectRouteToToRouteHelperRector/Fixture/skip_with_object_call.php.inc
tests/Rector/MethodCall/RedirectRouteToToRouteHelperRector/Fixture/skip_with_only_back.php.inc
tests/Rector/MethodCall/RedirectRouteToToRouteHelperRector/RedirectRouteToToRouteHelperRectorTest.php
tests/Rector/MethodCall/RedirectRouteToToRouteHelperRector/config/configured_rule.php

This PR adds a new rule `RedirectRouteToToRouteHelperRector` to refactor the code around the redirect route.
Most of the Laravel developers redirect to the route location with the code like this:
```php
return redirect()->route('home')->with('...');
```
But there is a Laravel helper called [to_route](https://laravel.com/docs/9.x/helpers#method-to-route) that can be called directly and the `redirect()` call is not needed. The above line can be rewritten as:
```php
return to_route('home')->with('...');
```

Add New Refactore Rule - Redirect Route To To Route Helper

---

docs/rector_rules_overview.md
src/Rector/FuncCall/RemoveDumpDataDeadCodeRector.php
tests/Rector/FuncCall/RemoveDumpDataDeadCodeRector/Fixture/fixture.php.inc
tests/Rector/FuncCall/RemoveDumpDataDeadCodeRector/Fixture/skip_as_if_condition.php.inc
tests/Rector/FuncCall/RemoveDumpDataDeadCodeRector/Fixture/skip_in_if_condition.php.inc
tests/Rector/FuncCall/RemoveDumpDataDeadCodeRector/Fixture/skip_with_object_call.php.inc
tests/Rector/FuncCall/RemoveDumpDataDeadCodeRector/Fixture/skip_with_relevant_name.php.inc
tests/Rector/FuncCall/RemoveDumpDataDeadCodeRector/RemoveDumpDataDeadCodeRectorTest.php
tests/Rector/FuncCall/RemoveDumpDataDeadCodeRector/config/configured_rule.php

This PR adds a new rule `RemoveDumpDataDeadCodeRector` to remove the unnecessary dump data code.
We are Humans And Human makes mistake sometimes we miss removing dump data code like `dd` or `dump` function calls.
That's why I added this new rector class to remove code that the developer forgot to remove.

[Laravel] Add RemoveDumpDataDeadCodeRector

---

docs/rector_rules_overview.md

This PR fixes a copy/paste error for the `RemoveDumpDataDeadCodeRector` heading.

Fix RemoveDumpDataDeadCodeRector heading

---

README.md
config/sets/laravel90.php
config/sets/level/up-to-laravel-90.php
src/Set/LaravelLevelSetList.php
src/Set/LaravelSetList.php

Add set for Laravel 9.x

---

src/Rector/Class_/AddMockConsoleOutputFalseToConsoleTestsRector.php

`SetUpClassMethodNodeManipulator` is removed at https://github.com/rectorphp/rector-phpunit/pull/90.
This PR handle it.

[Laravel] Handle SetUpClassMethodNodeManipulator service not found

---

composer.json

This PR updates Rector to the latest `0.14.7` release.

Update composer to Rector `0.14.7`

---

src/Rector/ClassMethod/AddGenericReturnTypeToRelationsRector.php

On Rector 0.15.2 the test failed to run for no-phpdoc.php.inc. This fix supports both 0.14.x and 0.15.x
It failed because of [this change](https://github.com/rectorphp/rector-src/commit/96c457badfd0c198a57a758c552ec82aee0049de#diff-d12d9867614cdc1cab5c7942a80cafabd78d8e027d227f9ba1bc8ffeb6643f61L70).

Fix AddGenericReturnTypeToRelationsRector on Rector 0.15.2

---

src/Rector/ClassMethod/AddGenericReturnTypeToRelationsRector.php
tests/Rector/ClassMethod/AddGenericReturnTypeToRelationsRector/Fixture/phpdoc-with-supported-return.php.inc

Only supported if the existing PHPDoc return type is the same as the native return type. This way we ensure that we don't change types. 
Not updating of another type was already covered with a test. I added a test for the case when we can update the PHPDoc with only the generics.

Support updating an existing return type with generics

---

.github/workflows/code_analysis.yaml
easy-ci.php

As I find the code_analysis very important I researched the problem and found it. The problem lies in [this commit](https://github.com/rectorphp/reusable-workflows/commit/f2da03392acc3c7df6387862c384e7651b98bf3e) in the reusable-workflows repository. The fetching of a default easy-ci.php is removed. Thats why I grabbed the one from rector-doctrine. Did not have to change anything to our needings at all.

Fix `check-active-classes` and re-enable code_analysis workflow

---

config/sets/laravel90.php

This way contributors don't get errors when using `composer run check-cs` locally.

Fix code-style using `fix-cs` command

---

.github/workflows/code_analysis.yaml
src/NodeAnalyzer/LumenRouteRegisteringMethodAnalyzer.php

Run only on PR's from branches on main repository (from core contributors), not on the forks or PR's from forks.

Fix Rector job on PR to main repository

---

.github/workflows/code_analysis.yaml

With my previous change it ran inside my fork itself, thus in PR's from rene-bos/some-branch to rene-bos/main. We also don't want that offcourse 😉.

Don't run Rector job inside forks

---

.github/workflows/downgraded_release.yaml
build/composer-php-72.json
build/rector-downgrade-php-72.php
src/Rector/StaticCall/RequestStaticValidateToInjectRector.php

This PR adds the ability to downgrade the PHP version and tag a new release.
See: 
- https://tomasvotruba.com/blog/how-to-release-php-81-and-72-package-in-the-same-repository/
- https://github.com/TomasVotruba/cognitive-complexity/blob/main/.github/workflows/downgraded_release.yaml
- https://github.com/symplify/config-transformer/blob/main/.github/workflows/downgraded_release.yaml

Add ability to auto downgrade tag release

---

.github/workflows/downgraded_release.yaml
src/Rector/StaticCall/RequestStaticValidateToInjectRector.php

This PR fixes an issue with downgrading the PHP version

Fix issue with downgraded PHP

---

config/sets/laravel-code-quality.php
config/sets/laravel-facade-aliases-to-full-names.php
src/Set/LaravelSetList.php

For cases when you want to skip this refactoring (Change Facade aliases into full facade names), like in this issue https://github.com/driftingly/rector-laravel/issues/95, you have to opt out of the Code Style set entirely.
This PR extracts that refactoring into a set of its own, so we can use it only if we need it.

Extract rule for Facade aliases in their own set

---

src/Rector/StaticCall/RouteActionCallableRector.php
tests/Rector/StaticCall/RouteActionCallableRector/Fixture/named_route_with_middleware.php.inc
tests/Rector/StaticCall/RouteActionCallableRector/Fixture/only_array_route.php.inc
tests/Rector/StaticCall/RouteActionCallableRector/Fixture/route_with_middleware.php.inc

Allows refactoring of routes using the array with `uses` as a single key and arrays that outside of the `name` key are using `middleware` one.

Route callable improvement

---

src/Rector/Empty_/EmptyToBlankAndFilledFuncRector.php
tests/Rector/Empty_/EmptyToBlankAndFilledFuncRector/EmptyToBlankAndFilledFuncRectorTest.php
tests/Rector/Empty_/EmptyToBlankAndFilledFuncRector/Fixture/fixture_with_empty.php.inc
tests/Rector/Empty_/EmptyToBlankAndFilledFuncRector/Fixture/fixture_with_not_empty.php.inc
tests/Rector/Empty_/EmptyToBlankAndFilledFuncRector/config/configured_rule.php

* Adds the `RectorLaravel\Rector\Empty_\EmptyToBlankAndFilledFuncRector` rule
* Adds a test for the rule.
In the Laravel framework, there are two helpers, [blank()](https://laravel.com/docs/10.x/helpers#method-blank) and [filled()](https://laravel.com/docs/10.x/helpers#method-filled), which are better replacements for PHP's built-in `empty()` construct, as it has some odd behaviours.

Empty() to Blank() or Filled() refactor rule

---

src/Rector/MethodCall/AssertStatusToAssertMethodRector.php
tests/Rector/MethodCall/AssertStatusToAssertMethodRector/AssertStatusToAssertMethodTest.php
tests/Rector/MethodCall/AssertStatusToAssertMethodRector/Fixture/fixture_with_illuminate_response_constants.php.inc
tests/Rector/MethodCall/AssertStatusToAssertMethodRector/Fixture/fixture_with_magic_numbers.php.inc

* Adapted the `AssertStatusToAssertMethodRector` to handle 410, 500 and 503 status codes.
* Updates the test to reflect the changes.
* Updates the test to use a static data provider method.
Updates the `AssertStatusToAssertMethodRector` with the [new HTTP assertion methods introduced in 10.9](https://laravel-news.com/laravel-10-9-0).
There might be some issues here with a requirement to configure which version of Laravel you're using otherwise you might end up with broken method calls because the method doesn't exist. I'm not sure of the best way to apply this. A configuration to specify which HTTP statuses to refactor.
There's also a minor fix to make the test for this use a static data provider.

Adds Gone, InternalServerError & ServiceUnavailable statuses to AssertStatusToAssertMethodRector

---

src/Rector/ClassMethod/AddArgumentDefaultValueRector.php
src/Rector/Empty_/EmptyToBlankAndFilledFuncRector.php
src/Rector/MethodCall/AssertStatusToAssertMethodRector.php
src/Rector/MethodCall/RedirectBackToBackHelperRector.php
src/Rector/MethodCall/RedirectRouteToToRouteHelperRector.php
src/Rector/StaticCall/RouteActionCallableRector.php
tests/Rector/MethodCall/AssertStatusToAssertMethodRector/config/configured_rule.php
tests/Rector/MethodCall/RedirectBackToBackHelperRector/Fixture/fixture_with_argument.php.inc
tests/Rector/MethodCall/RedirectBackToBackHelperRector/Fixture/fixture_without_with.php.inc
tests/Rector/MethodCall/RedirectRouteToToRouteHelperRector/Fixture/fixture_without_with.php.inc
tests/Rector/MethodCall/RedirectRouteToToRouteHelperRector/Fixture/without_with_fixture.php.inc

This pull request resolves issue #78. The issue was related to an error occurring when using the `redirect()->route()` method. The bug has been identified and fixed.
**Changes:**
- Analyzed the root cause of the error and determined that it was due to incorrect parameter handling in the `redirect()->back()` method.
- Refactored Some old files code
**Testing:**
Added new unit tests specifically targeting the scenario described in issue #78 to verify the fix.
Ran the full test suite locally to ensure that all existing tests pass successfully.
Manually tested the affected functionality, verifying that the error no longer occurs.

Fix Issue #78 - Error in Redirect::route() Method

---

docs/rector_rules_overview.md
src/Rector/FuncCall/NowFuncWithStartOfDayMethodCallToTodayFuncRector.php
tests/Rector/FuncCall/NowFuncWithStartOfDayMethodCallToTodayFuncRector/Fixture/fixture.php.inc
tests/Rector/FuncCall/NowFuncWithStartOfDayMethodCallToTodayFuncRector/Fixture/skip_now_with_other_calls.php.inc
tests/Rector/FuncCall/NowFuncWithStartOfDayMethodCallToTodayFuncRector/NowFuncWithStartOfDayMethodCallToTodayFuncRectorTest.php
tests/Rector/FuncCall/NowFuncWithStartOfDayMethodCallToTodayFuncRector/config/configured_rule.php

* Adds the new rule
* Adds tests for the rule
* Adds documentation for said rule
The `today()` helper exists in Laravel, providing the date today but set at the start of the day. It makes sense, where possible, to remove the use of `now()` for `today()` when this is the case.

New `now()->startOfDay()` to `today()` rule

---

docs/rector_rules_overview.md
src/Rector/Expr/SubStrToStartsWithOrEndsWithStaticMethodCallRector/SubStrToStartsWithOrEndsWithStaticMethodCallRector.php
tests/Rector/Expr/SubStrToStartsWithOrEndsWithStaticMethodCallRector/Fixture/fixture.php.inc
tests/Rector/Expr/SubStrToStartsWithOrEndsWithStaticMethodCallRector/Fixture/skips_non_ends_with.php.inc
tests/Rector/Expr/SubStrToStartsWithOrEndsWithStaticMethodCallRector/Fixture/skips_non_starts_with.php.inc
tests/Rector/Expr/SubStrToStartsWithOrEndsWithStaticMethodCallRector/SubStrToStartsWithOrEndsWithStaticMethodCallRectorTest.php
tests/Rector/Expr/SubStrToStartsWithOrEndsWithStaticMethodCallRector/config/configured_rule.php

* Adds the new rule for processing `substr()` using Laravel's Str helper for `startsWith()` or `endsWith()` where appropriate.
* Adds tests
* Adds documentation
Often older projects will use the substring method, allowing the end user to switch these out quickly.

substring to Str::startsWith or Str::endsWith

---

README.md
composer.json
config/sets/laravel-static-to-injection.php
docs/rector_rules_overview.md
src/Contract/ValueObject/ArgumentFuncCallToMethodCallInterface.php
src/Rector/Expr/SubStrToStartsWithOrEndsWithStaticMethodCallRector/SubStrToStartsWithOrEndsWithStaticMethodCallRector.php
src/Rector/FuncCall/ArgumentFuncCallToMethodCallRector.php
src/Rector/FuncCall/NotFilledBlankFuncCallToBlankFilledFuncCallRector.php
src/Rector/FuncCall/NowFuncWithStartOfDayMethodCallToTodayFuncRector.php
src/ValueObject/ArgumentFuncCallToMethodCall.php
src/ValueObject/ArrayFuncCallToMethodCall.php
tests/Rector/FuncCall/ArgumentFuncCallToMethodCallRector/ArgumentFuncCallToMethodCallRectorTest.php
tests/Rector/FuncCall/ArgumentFuncCallToMethodCallRector/Fixture/back.php.inc
tests/Rector/FuncCall/ArgumentFuncCallToMethodCallRector/Fixture/broadcast.php.inc
tests/Rector/FuncCall/ArgumentFuncCallToMethodCallRector/Fixture/config.php.inc
tests/Rector/FuncCall/ArgumentFuncCallToMethodCallRector/Fixture/route.php.inc
tests/Rector/FuncCall/ArgumentFuncCallToMethodCallRector/Fixture/session.php.inc
tests/Rector/FuncCall/ArgumentFuncCallToMethodCallRector/Fixture/skip_static_method.php.inc
tests/Rector/FuncCall/ArgumentFuncCallToMethodCallRector/Fixture/view.php.inc
tests/Rector/FuncCall/ArgumentFuncCallToMethodCallRector/config/configured_rule.php
tests/Rector/FuncCall/NotFilledBlankFuncCallToBlankFilledFuncCallRector/config/configured_rule.php
tests/Rector/FuncCall/NowFuncWithStartOfDayMethodCallToTodayFuncRector/config/configured_rule.php

This PR moves the `ArgumentFuncCallToMethodCallRector` class from Rector to Rector Laravel. 
See https://github.com/rectorphp/rector-src/pull/3774#issuecomment-1539905216

Move `ArgumentFuncCallToMethodCallRector` to package

---

composer.json
config/sets/laravel-static-to-injection.php
src/NodeFactory/AppAssignFactory.php
src/Rector/Assign/CallOnAppArrayAccessToStandaloneAssignRector.php
src/Rector/ClassMethod/MigrateToSimplifiedAttributeRector.php
src/Rector/Class_/PropertyDeferToDeferrableProviderToRector.php
src/Rector/Class_/UnifyModelDatesWithCastsRector.php
src/Rector/FuncCall/ArgumentFuncCallToMethodCallRector.php
src/Rector/FuncCall/RemoveDumpDataDeadCodeRector.php
src/Rector/MethodCall/ChangeQueryWhereDateValueWithCarbonRector.php
src/Rector/MethodCall/RedirectBackToBackHelperRector.php
src/Rector/MethodCall/RedirectRouteToToRouteHelperRector.php
src/Rector/New_/AddGuardToLoginEventRector.php
src/Rector/PropertyFetch/OptionalToNullsafeOperatorRector.php
tests/Rector/Assign/CallOnAppArrayAccessToStandaloneAssignRector/Fixture/some_fixture.php.inc
tests/Rector/FuncCall/ArgumentFuncCallToMethodCallRector/Fixture/auth.php.inc
tests/Rector/FuncCall/ArgumentFuncCallToMethodCallRector/config/configured_rule.php
tests/Rector/New_/AddGuardToLoginEventRector/Fixture/without_assignment.php.inc

Issue https://github.com/driftingly/rector-laravel/issues/115.

Support for Rector 0.17.1

---

composer.json
config/config.php
src/Rector/FuncCall/SleepFuncToSleepStaticCallRector.php

The base `config.php` file is now practically empty, but I did not delete it.
I tried deleting it and all the places where it was imported, and all tests still passed. They did not delete it in the core because they still had to keep some configuration there, and we might want to do the same in the future.
This PR would fix https://github.com/driftingly/rector-laravel/issues/125.

Updated config to use the new Laravel DI Container

---

config/sets/laravel100.php

The deprecated `getBaseQuery` was initially removed, but then it was [added back](https://github.com/laravel/framework/pull/41923) because it caused a regression.
Closes #129

Remove reverted Laravel 10 rule (getBaseQuery -> toBase)

---

config/sets/laravel80.php

It references the commit where the function was "renamed", but the next commit in the laravel/framework repository is re-adding the function.
https://github.com/laravel/framework/commit/8e0914e847e8b161a1968a68f9f80003e23136db
As `assertExactJson()` and `assertSimilarJson()` have very different expectations, I think this could change could inadvertently alter tests to be less accurate.

Remove MethodCallRename rule from Laravel80 ruleset

---

docs/rector_rules_overview.md
src/Rector/Expr/AppEnvironmentComparisonToParameterRector.php
tests/Rector/Expr/AppEnvironmentComparisonToParameterRector/AppEnvironmentComparisonToParameterRectorTest.php
tests/Rector/Expr/AppEnvironmentComparisonToParameterRector/Fixture/fixture.php.inc
tests/Rector/Expr/AppEnvironmentComparisonToParameterRector/Fixture/skip_if_already_using_parameter.php.inc
tests/Rector/Expr/AppEnvironmentComparisonToParameterRector/Fixture/skip_if_not_application_object.php.inc
tests/Rector/Expr/AppEnvironmentComparisonToParameterRector/Fixture/skip_if_not_comparing_to_string.php.inc
tests/Rector/Expr/AppEnvironmentComparisonToParameterRector/Fixture/skip_if_not_using_facade.php.inc
tests/Rector/Expr/AppEnvironmentComparisonToParameterRector/config/configured_rule.php

Creates the following rule:
Replace `$app->environment() === 'local'` with `$app->environment('local'])`
- class: [`RectorLaravel\Rector\Expr\AppEnvironmentComparisonToParameterRector`](../src/Rector/Expr/AppEnvironmentComparisonToParameterRector.php)
```diff
-$app->environment() === 'production';
+$app->environment('production');
```
This rule will handle scenarios such as if the Facade is used or the Application contract.

Adds AppEnvironmentComparisonToParameterRector rule

---

docs/rector_rules_overview.md
src/Rector/MethodCall/UseComponentPropertyWithinCommandsRector.php
tests/Rector/MethodCall/UseComponentPropertyWithinCommandsRector/Fixture/fixture.php.inc
tests/Rector/MethodCall/UseComponentPropertyWithinCommandsRector/Fixture/skip_non_command_extending_classes.php.inc
tests/Rector/MethodCall/UseComponentPropertyWithinCommandsRector/Fixture/skip_non_component_methods.php.inc
tests/Rector/MethodCall/UseComponentPropertyWithinCommandsRector/UseComponentPropertyWithinCommandsRectorTest.php
tests/Rector/MethodCall/UseComponentPropertyWithinCommandsRector/config/configured_rule.php

Adds a new rule to refactor commands and make use of the component property that handles using Termwind output like most of the Laravel commands have used.
Use `$this->components` property within commands
- class: [`RectorLaravel\Rector\MethodCall\UseComponentPropertyWithinCommandsRector`](../src/Rector/MethodCall/UseComponentPropertyWithinCommandsRector.php)
```diff
use Illuminate\Console\Command;
class CommandWithComponents extends Command
{
public function handle()
{
-        $this->ask('What is your name?');
-        $this->line('A line!');
-        $this->info('Info!');
-        $this->error('Error!');
+        $this->components->ask('What is your name?');
+        $this->components->line('A line!');
+        $this->components->info('Info!');
+ …
```

Adds UseComponentPropertyWithinCommandsRector rule

---

docs/rector_rules_overview.md
src/Rector/MethodCall/EloquentWhereTypeHintClosureParameterRector.php
tests/Rector/MethodCall/EloquentWhereTypeHintClosureParameterRector/EloquentWhereTypeHintClosureParameterRectorTest.php
tests/Rector/MethodCall/EloquentWhereTypeHintClosureParameterRector/Fixture/fixture.php.inc
tests/Rector/MethodCall/EloquentWhereTypeHintClosureParameterRector/Fixture/fixture2.php.inc
tests/Rector/MethodCall/EloquentWhereTypeHintClosureParameterRector/Fixture/fixture3.php.inc
tests/Rector/MethodCall/EloquentWhereTypeHintClosureParameterRector/Fixture/skip_non_closure_argument.php.inc
tests/Rector/MethodCall/EloquentWhereTypeHintClosureParameterRector/Fixture/skip_non_query_object.php.inc
tests/Rector/MethodCall/EloquentWhereTypeHintClosureParameterRector/config/configured_rule.php

Adds a new rule to help add type hinting in a similar way to #138 
Change typehint of closure parameter in where method of Eloquent Builder
- class: [`RectorLaravel\Rector\MethodCall\EloquentWhereTypeHintClosureParameterRector`](../src/Rector/MethodCall/EloquentWhereTypeHintClosureParameterRector.php)
```diff
-$query->where(function ($query) {
+$query->where(function (\Illuminate\Contracts\Database\Eloquent\Builder $query) {
$query->where('id', 1);
});
```
Covers both static use with a Model and the instant's use on the builder.

Adds the EloquentWhereTypeHintClosureParameterRector

---

docs/rector_rules_overview.md
src/Rector/MethodCall/EloquentOrderByToLatestOrOldestRector.php
tests/Rector/MethodCall/EloquentOrderByToLatestOrOldestRector/EloquentOrderByToLatestOrOldestRectorTest.php
tests/Rector/MethodCall/EloquentOrderByToLatestOrOldestRector/Fixture/fixture.php.inc
tests/Rector/MethodCall/EloquentOrderByToLatestOrOldestRector/Fixture/skip_if_not_eloquent_builder.php.inc
tests/Rector/MethodCall/EloquentOrderByToLatestOrOldestRector/Fixture/skip_if_not_enough_arguments.php.inc
tests/Rector/MethodCall/EloquentOrderByToLatestOrOldestRector/config/configured_rule.php

Created a new rule for swapping out `orderBy` or `orderByDesc` to use `latest` or `oldest` instead.
Changes `orderBy()` to `latest()` or `oldest()`
- class: [`RectorLaravel\Rector\MethodCall\EloquentOrderByToLatestOrOldestRector`](../src/Rector/MethodCall/EloquentOrderByToLatestOrOldestRector.php)
```diff
use Illuminate\Database\Eloquent\Builder;
-$builder->orderBy('created_at');
-$builder->orderBy('created_at', 'desc');
-$builder->orderBy('deleted_at');
+$builder->latest();
+$builder->oldest();
+$builder->latest('deleted_at');
```

Adds the EloquentOrderByToLatestOrOldestRector rule

---

docs/rector_rules_overview.md
src/Rector/MethodCall/EloquentOrderByToLatestOrOldestRector.php
tests/Rector/MethodCall/EloquentOrderByToLatestOrOldestRector/Fixture/fixture.php.inc

Fixes a mistake with `latest()` and `oldest()` being the wrong way around.
Brough up as a problem in #142

Fixes a mix up between latest() and oldest()

---

docs/rector_rules_overview.md
src/Rector/MethodCall/EloquentOrderByToLatestOrOldestRector.php
tests/Rector/MethodCall/EloquentOrderByToLatestOrOldestRector/Fixture/fixture.php.inc
tests/Rector/MethodCall/EloquentOrderByToLatestOrOldestRector/Fixture/skip_if_column_not_allowed.php.inc
tests/Rector/MethodCall/EloquentOrderByToLatestOrOldestRector/config/configured_rule.php

Resolves #147.
- Allows an `ALLOWED_PATTERNS` array of strings to apply this rule to
- Adds additional test items for variable handling
- The way this is implemented, it will always change `created_at` columns (as it did before)
- Because static analysis cannot get the value of a variable, we instead allow for specifying variable names
- Current test scenario
- Scenario where no rule configuration is present

Allow configuring EloquentOrderByToLatestOrOldestRector

---

config/sets/laravel100.php
docs/rector_rules_overview.md
src/Rector/StaticCall/ReplaceAssertTimesSendWithAssertSentTimesRector.php
tests/Rector/StaticCall/ReplaceAssertTimesSendWithAssertSentTimesRector/Fixture/fixture.php.inc
tests/Rector/StaticCall/ReplaceAssertTimesSendWithAssertSentTimesRector/Fixture/skips_other_facades.php.inc
tests/Rector/StaticCall/ReplaceAssertTimesSendWithAssertSentTimesRector/Fixture/skips_other_methods.php.inc
tests/Rector/StaticCall/ReplaceAssertTimesSendWithAssertSentTimesRector/ReplaceAssertTimesSendWithAssertSentTimesRectorTest.php
tests/Rector/StaticCall/ReplaceAssertTimesSendWithAssertSentTimesRector/config/configured_rule.php

The rule should work on the Notification facade. I've added the rules to the Laravel100 config 
[PR when the method was removed for Laravel 10](https://github.com/laravel/framework/pull/41136/files#diff-79076a209637866c842a9e9db32a961de43cfa12a3dd8bdfaf95694484dcee7b)

[Laravel100] Swap assertTimesSent with assertSentTimes

---

src/Rector/MethodCall/JsonCallToExplicitJsonCallRector.php
tests/Rector/MethodCall/JsonCallToExplicitJsonCallRector/Fixture/fixture_with_json_calls.php.inc
tests/Rector/MethodCall/JsonCallToExplicitJsonCallRector/Fixture/fixture_with_json_calls_to_skip.php.inc
tests/Rector/MethodCall/JsonCallToExplicitJsonCallRector/JsonCallToExplicitJsonCallRectorTest.php
tests/Rector/MethodCall/JsonCallToExplicitJsonCallRector/config/configured_rule.php

Adds the following rule:
Changes Method Calls of `$this->json()` in PHPUnit Feature Tests to the more explicit version `$this->postJson()`, $this->putJson(), etc..
* class: [`\RectorLaravel\Rector\MethodCall\JsonCallToExplicitJsonCallRector`](../src/Rector/MethodCall/JsonCallToExplicitJsonCallRector.php)
```diff
-$this->json("POST", "/api/v1/users", $data);
+$this->postJson("/api/v1/users", $data);
-$this->json("PUT", "/api/v1/users", $data);
+$this->putJson("/api/v1/users", $data);
```

Add JsonCallToExplicitJsonCallRector

---

build/composer-php-72.json
composer.json

This PR adds the supported Rector version to the downgraded tagged version.
Bump PHP version to 8.2 after adding `LevelSetList::UP_TO_PHP_82` to Rector config.
Closes #150

Bump PHP and add rector to downgraded composer

---

.github/workflows/downgraded_release.yaml

This PR bumps the PHP version in the downgrade action to PHP 8.2

Update downgrade script for new PHP version

---

config/sets/laravel100.php
docs/rector_rules_overview.md
src/Rector/MethodCall/ReplaceWithoutJobsEventsAndNotificationsWithFacadeFakeRector.php
tests/Rector/MethodCall/ReplaceWithoutJobsEventsAndNotificationsWithFacadeFakeRector/Fixture/fixture.php.inc
tests/Rector/MethodCall/ReplaceWithoutJobsEventsAndNotificationsWithFacadeFakeRector/Fixture/skip_non_test_case.php.inc
tests/Rector/MethodCall/ReplaceWithoutJobsEventsAndNotificationsWithFacadeFakeRector/ReplaceWithoutJobsEventsAndNotificationsWithFacadeFakeRectorTest.php
tests/Rector/MethodCall/ReplaceWithoutJobsEventsAndNotificationsWithFacadeFakeRector/config/configured_rule.php

Another change related to the deprecated trait
```diff
-$this->withoutJobs();
-$this->withoutEvents();
-$this->withoutNotifications();
+\Illuminate\Support\Facades\Bus::fake();
+\Illuminate\Support\Facades\Event::fake();
+\Illuminate\Support\Facades\Notification::fake();
```
This should be pretty straight forward when used to stop no Jobs/Events/Notifications to be fired during tests.

Replaces without jobs/events/notifications to the appropriate facade

---

build/composer-php-72.json
composer.json
phpstan.neon

This PR removes the deprecated `rector/phpstan-rules` package.
https://github.com/rectorphp/phpstan-rules#deprecated---switch-to-symplifyphpstan-rules

Remove deprecated `rector/phpstan-rules`

---

docs/rector_rules_overview.md
src/Rector/StaticCall/EloquentMagicMethodToQueryBuilderRector.php
stubs/Illuminate/Database/Eloquent/Builder.php
tests/Rector/StaticCall/EloquentMagicMethodToQueryBuilderRector/Fixture/with_exclude_methods.php.inc
tests/Rector/StaticCall/EloquentMagicMethodToQueryBuilderRector/config/configured_rule.php

Add ability to exclude methods from the rector `EloquentMagicMethodToQueryBuilderRector`
I found this beneficial for `find()` and `findOrFail()`, as these are often used in simple statements without chaining, and subjectively appear overly verbose when `::query()->` is added to them.
e.g.
```php
<?php
declare(strict_types=1);
use RectorLaravel\Rector\MethodCall\EloquentOrderByToLatestOrOldestRector;
use Rector\Config\RectorConfig;
return static function (RectorConfig $rectorConfig): void {
$containerConfigurator->extension('rectorConfig', [
[
'class' => EloquentMagicMethodToQueryBuilderRector::class,
'configuration' => [
'exclude_methods' => [
'find',
'findOrFail',
],
],
],
]);
};
```
↓
```diff
use App\Models\User;
$user = User::find(1); // no change
-$user = User::where('x', 1);
+$user = …
```

Add method exclusions for `EloquentMagicMethodToQueryBuilderRector`

---

composer.json
docs/rector_rules_overview.md
src/Rector/MethodCall/JsonCallToExplicitJsonCallRector.php
src/Rector/StaticCall/EloquentMagicMethodToQueryBuilderRector.php

* Corrects the sample docs of the EloquentMagicMethodToQueryBuilderRector rule
* Docs updated.
Without this fix the `composer docs` script fails to generate the new rules documentation for the repo
I'm not sure why the command is now removing lots of examples. Possible that they've been added manually?

[Fix] EloquentMagicMethodToQueryBuilderRector provides incorrect doc sample

---

README.md
config/sets/laravel110.php
config/sets/level/up-to-laravel-110.php
docs/rector_rules_overview.md
src/Rector/Class_/ModelCastsPropertyToCastsMethodRector.php
src/Set/LaravelLevelSetList.php
src/Set/LaravelSetList.php
tests/Rector/Class_/ModelCastsPropertyToCastsMethodRector/Fixture/fixture.php.inc
tests/Rector/Class_/ModelCastsPropertyToCastsMethodRector/Fixture/skip_class_with_casts_method.php.inc
tests/Rector/Class_/ModelCastsPropertyToCastsMethodRector/Fixture/skip_non_model_classes.php.inc
tests/Rector/Class_/ModelCastsPropertyToCastsMethodRector/ModelCastsPropertyToCastsMethodRectorTest.php
tests/Rector/Class_/ModelCastsPropertyToCastsMethodRector/config/configured_rule.php

* Adds a rule to change the `$casts` property to a `casts()` class method.
* Adds the Laravel 11 group
* Adds tests for the new rule
* Generates documentation
This is [a new bit of functionality for Laravel 11](https://benjamincrozat.com/laravel-11#new-feature-the-new-and-more-convenient-modelcasts-method-goes-live-laravel-11).
[The PR in Laravel](https://github.com/laravel/framework/pull/47237)
Doc were generated with the fix from #172 so it's removed lots of examples.

[Laravel110] Adds ModelCastsPropertyToCastsMethodRector rule

---

docs/rector_rules_overview.md
src/Rector/FuncCall/RemoveRedundantValueCallsRector.php
src/Rector/FuncCall/RemoveRedundantWithCallsRector.php
tests/Rector/FuncCall/RemoveRedundantValueCallsRector/Fixture/fixture.php.inc
tests/Rector/FuncCall/RemoveRedundantValueCallsRector/Fixture/skips_object_without_an_obvious_type.php.inc
tests/Rector/FuncCall/RemoveRedundantValueCallsRector/RemoveRedundantValueCallsRectorTest.php
tests/Rector/FuncCall/RemoveRedundantValueCallsRector/Source/HelperObject.php
tests/Rector/FuncCall/RemoveRedundantValueCallsRector/config/configured_rule.php
tests/Rector/FuncCall/RemoveRedundantWithCallsRector/Fixture/fixture.php.inc
tests/Rector/FuncCall/RemoveRedundantWithCallsRector/Fixture/skips_calls_with_callables_as_a_second_arg.php.inc
tests/Rector/FuncCall/RemoveRedundantWithCallsRector/Fixture/skips_object_without_an_obvious_type.php.inc
tests/Rector/FuncCall/RemoveRedundantWithCallsRector/RemoveRedundantWithCallsRectorTest.php
tests/Rector/FuncCall/RemoveRedundantWithCallsRector/Source/HelperObject.php
tests/Rector/FuncCall/RemoveRedundantWithCallsRector/config/configured_rule.php

* Adds a rule for removing redundant with() helper usage
* Adds a rule for removing redundant value() helper usage
* Adds tests for both new rules
* Updates rule list
Based on rules from Larastan. These are quite simple little use cases where we can remove the use of a helper when it's not needed.
```diff
-value(new Object())->something();
+(new Object())->something();
```
-with(new Object())->something();
+(new Object())->something();
value() => https://github.com/larastan/larastan/blob/2.x/src/Rules/UselessConstructs/NoUselessValueFunctionCallsRule.php
with() => https://github.com/larastan/larastan/blob/2.x/src/Rules/UselessConstructs/NoUselessWithFunctionCallsRule.php

[CodeQuality] Adds rules for the with and value helpers

---

src/Rector/If_/ThrowIfRector.php
tests/Rector/If_/ThrowIfRector/Fixture/fixture.php.inc
tests/Rector/If_/ThrowIfRector/Fixture/skip_where_condition_contains_assigns_var_for_exception.php.inc

* alters the IfThrowRector rule
* adds more test scenarios
Sometimes the rule could generate broken code where a variable might not exist as it's created in the If statement's condition. In this instance the rule shouldn't make any changes.
```php
if ($foo && $bar = call()) {
throw new Exception($foo, $bar);
}
```

Adds a fix for ThrowIfRector causing issues with assigned vars

---

docs/rector_rules_overview.md
src/Rector/FuncCall/ThrowIfAndThrowUnlessExceptionsToUseClassStringRector.php
tests/Rector/FuncCall/ThrowIfAndThrowUnlessExceptionsToUseClassStringRector/Fixture/fixture.php.inc
tests/Rector/FuncCall/ThrowIfAndThrowUnlessExceptionsToUseClassStringRector/Fixture/skip_where_already_using_class_string.php.inc
tests/Rector/FuncCall/ThrowIfAndThrowUnlessExceptionsToUseClassStringRector/ThrowIfAndThrowUnlessExceptionsToUseClassStringRectorTest.php
tests/Rector/FuncCall/ThrowIfAndThrowUnlessExceptionsToUseClassStringRector/config/configured_rule.php

* New rule
* Tests for the rule
* Docs update
A nice little rule to change the parameters of `throw_if()` and `throw_unless()` to use a class string.
```diff
-throw_if($condition, new MyException('custom message'));
+throw_if($condition, MyException::class, 'custom message');
```

Adds the ThrowIFAndThrowUnlessExceptionsToUseClassStringRector rule

---

docs/rector_rules_overview.md
src/Rector/MethodCall/ValidationRuleArrayStringValueToArrayRector.php
tests/Rector/MethodCall/ValidationRuleArrayStringValueToArrayRector/Fixture/SkipNonFormRequestClass.php.inc
tests/Rector/MethodCall/ValidationRuleArrayStringValueToArrayRector/Fixture/applies_to_classes_extending_form_request.php.inc
tests/Rector/MethodCall/ValidationRuleArrayStringValueToArrayRector/Fixture/fixture.php.inc
tests/Rector/MethodCall/ValidationRuleArrayStringValueToArrayRector/Fixture/skip_form_request_non_rules_class_method.php.inc
tests/Rector/MethodCall/ValidationRuleArrayStringValueToArrayRector/Fixture/skips_arrays_with_sub_arrays_already.php.inc
tests/Rector/MethodCall/ValidationRuleArrayStringValueToArrayRector/Fixture/skips_non_validator_method_call.php.inc
tests/Rector/MethodCall/ValidationRuleArrayStringValueToArrayRector/ValidationRuleArrayStringValueToArrayRectorTest.php
tests/Rector/MethodCall/ValidationRuleArrayStringValueToArrayRector/config/configured_rule.php

* Adds the ValidationRuleArrayStringValueToArrayRector rule.
* adds tests for the rule
* update the docs
It would be neat to automatically configure validation rules that are in the single string format to become arrays.
e.g.
```diff
Validator::make($data, [
-    'field' => 'required|nullable|string|max:255',
+    'field' => ['required', 'nullable', 'string', 'max:255'],
]);
```
This rule will also work with the Validator facade and classes that extend the FormRequest class and have a rules method.

Validation Rule string value to Array

---

config/sets/laravel54.php

This PR drops renaming `every` to `nth` for collections. 
This rule is only valid when upgrading from 5.3 to 5.4 but continues to run for all sets.
Fixes #186

Drop renaming collection `every` to `nth`

---

docs/rector_rules_overview.md
src/Rector/MethodCall/ReplaceServiceContainerCallArgRector.php
src/ValueObject/ReplaceServiceContainerCallArg.php
tests/Rector/MethodCall/ReplaceServiceContainerCallArgRector/Fixture/fixture.php.inc
tests/Rector/MethodCall/ReplaceServiceContainerCallArgRector/Fixture/skip_non_configured_services.php.inc
tests/Rector/MethodCall/ReplaceServiceContainerCallArgRector/Fixture/skip_non_matching_classes.php.inc
tests/Rector/MethodCall/ReplaceServiceContainerCallArgRector/Fixture/skip_non_matching_method_calls.php.inc
tests/Rector/MethodCall/ReplaceServiceContainerCallArgRector/ReplaceServiceContainerCallArgRectorTest.php
tests/Rector/MethodCall/ReplaceServiceContainerCallArgRector/config/configured_rule.php

Adds a new ReplaceServiceContainerCallArgRector rule
Adds a ReplaceServiceContainerCallArg value object
Adds tests
Updates the docs
A neat little rule here which can be used in a set in the future to remove uses of string alias' to the service container.
```diff
-app('encrypter')->encrypt('...');
-\Illuminate\Support\Facades\Application::make('encrypter')->encrypt('...');
+app(Illuminate\Contracts\Encryption\Encrypter::class)->encrypt('...');
+\Illuminate\Support\Facades\Application::make(Illuminate\Contracts\Encryption\Encrypter::class)->encrypt('...');
```
Configuration of the rule is as simple as:
```php
new ReplaceServiceContainerCallArg(
'encrypter',
new ClassConstFetch(
new FullyQualified('Illuminate\Contracts\Encryption\Encrypter'),
'class'
),
),
```
You can also do it the other …

Adds ReplaceServiceContainerCallArgRector

---

composer.json

Currently, the build fails because installing the packages allows for `nikic/php-parser` to install the latest version (^5.0) but currently the new API for v5 breaks PHPStan but resolving the PHPStan issues will cause the tests to fail. For now, locking the dev requirement keeps the build working as expected and doesn't appear to affect the running of tests.

Add nikic/php-parser and sort packages

---

src/Rector/FuncCall/RemoveRedundantValueCallsRector.php
src/Rector/FuncCall/RemoveRedundantWithCallsRector.php

Replace the use of AbstractScopeAwareRector for just AbstractRector.
A small clean up from two previous rules I wrote that didn't require extending AbstractScopeAwareRector.

Refactor to stop using AbstractScopeAwareRector

---

config/sets/laravel-if-helpers.php
docs/rector_rules_overview.md
rector.php
src/Rector/If_/AbortIfRector.php
src/Rector/If_/ReportIfRector.php
tests/Rector/If_/AbortIfRector/AbortIfRectorTest.php
tests/Rector/If_/AbortIfRector/Fixture/fixture.php.inc
tests/Rector/If_/AbortIfRector/Fixture/skip_if_more_statements.php.inc
tests/Rector/If_/AbortIfRector/Fixture/skip_where_condition_contains_assigns_var_for_exception.php.inc
tests/Rector/If_/AbortIfRector/config/configured_rule.php
tests/Rector/If_/ReportIfRector/Fixture/fixture.php.inc
tests/Rector/If_/ReportIfRector/Fixture/skip_if_more_statements.php.inc
tests/Rector/If_/ReportIfRector/Fixture/skip_where_condition_contains_assigns_var_for_exception.php.inc
tests/Rector/If_/ReportIfRector/ReportIfRectorTest.php
tests/Rector/If_/ReportIfRector/config/configured_rule.php

* Adds rules for `abort_if` and `report_if` function calls as replacement for If statements containing `abort` or `report`.
* Adds tests for both rules
* Adds a set to handle the two new rules and the previous `throw_if` related rule. The set making it easier to just use all of them.
* Adds the `config` dir to rector
Makes sense to cover all the possible helpers and have a set that covers the three scenarios. The only one missing would be the Dispatchable trait static calls (dispatchIf) but it would require a new rule and feels a bit more niche compared to the helpers.

Refactor If statements to use helpers with conditionals and provides a set

---

config/sets/laravel110.php
docs/rector_rules_overview.md
src/Rector/MethodCall/RefactorBlueprintGeometryColumnsRector.php
tests/Rector/MethodCall/RefactorBlueprintGeometryColumnsRector/Fixture/fixture.php.inc
tests/Rector/MethodCall/RefactorBlueprintGeometryColumnsRector/Fixture/skip_non_blueprint_objects.php.inc
tests/Rector/MethodCall/RefactorBlueprintGeometryColumnsRector/Fixture/skip_non_matching_method_call.php.inc
tests/Rector/MethodCall/RefactorBlueprintGeometryColumnsRector/RefactorBlueprintGeometryColumnsRectorTest.php
tests/Rector/MethodCall/RefactorBlueprintGeometryColumnsRector/config/configured_rule.php

* Additional rule
* Tests for the rule
* Docs updates
* Adds the rule to the Laravel 11 set
Adds a new rule for Laravel 11 to cover Spatial types in migrations https://laravel.com/docs/11.x/upgrade#spatial-types
This probably doesn't cover all cases but is a good start at least. It's quite hard to follow all the changes in the PR.

[Laravel110] Blueprint geometry columns

---

config/sets/laravel60.php

Fixes #110 
The 3 rules can be safely removed, as the methods previously did not expect a second parameter ([framework change link](https://github.com/laravel/framework/commit/6c1e014943a508afb2c10869c3175f7783a004e1)).
The only class where the `as` parameter was put in the middle of two other parameters was `Illuminate/Database/Capsule/Manager::table()`, so I left that in the Laravel 6 set. The chances of extending it are small and, in that case, this rule would probably help.
Ideally, we'd also modify the original `ArgumentAdderRector` class to not add these default parameters in MethodCalls or StaticCalls, but that's another more complex problem.

Remove redundant ArgumentAdderRector for nullable arguments

---

config/sets/laravel90.php
stubs/Illuminate/Foundation/Application.php
stubs/Illuminate/Foundation/Exceptions/Handler.php
stubs/Illuminate/Mail/MailManager.php
stubs/Illuminate/Mail/Mailable.php
stubs/Illuminate/Mail/Mailer.php
stubs/Illuminate/Mail/Message.php
stubs/Illuminate/Notifications/Messages/MailMessage.php
stubs/Illuminate/Queue/Failed/FailedJobProviderInterface.php
stubs/Illuminate/Support/Enumerable.php
stubs/Illuminate/Testing/TestResponse.php
tests/Sets/Laravel90/Fixture/application_lang_path_new_attribute.php.inc
tests/Sets/Laravel90/Fixture/application_storage_path_new_attribute.php.inc
tests/Sets/Laravel90/Fixture/exceptions_handler_ignore_with_public_visibility.php.inc
tests/Sets/Laravel90/Fixture/failed_job_provider_interface_new_attribute.php.inc
tests/Sets/Laravel90/Fixture/method_renames.php.inc
tests/Sets/Laravel90/Fixture/model_touch_new_attribute.php.inc
tests/Sets/Laravel90/Laravel90Test.php
tests/Sets/Laravel90/Source/Collection.php
tests/Sets/Laravel90/config/configured_rule.php

Fixes https://github.com/driftingly/rector-laravel/issues/220.
This PR also handles similar cases in the Laravel 9 set, where we add redundant default variables, and covers with tests all the changes of the set.

Fix redundant default arguments in Laravel 9 Set

---

pint.json

https://github.com/driftingly/rector-laravel/issues/228
Adds a `pint.json` configuration that skips the new defaults for the rules `single_line_empty_body` and `concat_space`.

Fix code style

---

src/Rector/StaticCall/DispatchToHelperFunctionsRector.php
tests/Rector/StaticCall/DispatchToHelperFunctionsRector/Fixture/bus_dispatchable.php.inc
tests/Rector/StaticCall/DispatchToHelperFunctionsRector/Fixture/event_dispatchable.php.inc

This ensures a leading slash `\` is added to the namespace of the class that is newed up, ensuring the namespace is loaded from the root and not relative to the current namespace.
Currently this rector breaks my code as it changes the code into something that does not work.
```diff
@@ @@
public function handleTenant(TenantWithDatabase $tenant): void
{
$tenant->run(function (): void {
-            CreateTenantBrandingAvatarsJob::dispatch()->onQueue(Queue::CENTRAL);
+            dispatch(new App\Central\Jobs\CreateTenantBrandingAvatarsJob())->onQueue(Queue::CENTRAL);
});
}
}
----------- end diff -----------
Applied rules:
* DispatchToHelperFunctionsRector
```
Note the missing `\` before `App`. This results in a namespace that can not be resolved. And broken tests
But with the leading slash, …

Use FullyQualified for class instead of Name

---

src/Rector/MethodCall/JsonCallToExplicitJsonCallRector.php
stubs/Illuminate/Foundation/Testing/Concerns/MakesHttpRequests.php
tests/Rector/MethodCall/JsonCallToExplicitJsonCallRector/Fixture/fixture_with_json_calls.php.inc
tests/Rector/MethodCall/JsonCallToExplicitJsonCallRector/Fixture/fixture_with_json_calls_to_skip.php.inc
tests/Rector/MethodCall/JsonCallToExplicitJsonCallRector/Fixture/skip_invalid_get_json_calls.php.inc

Fixes https://github.com/driftingly/rector-laravel/issues/217.
This PR will ensure that the `route()` helper will receive the `$data` argument, which should produce the same behavior.
Some cases taken into account:
```php
$http->json('GET', route('home'));
$http->json('GET', route('home'), ['payload']);
$http->json('GET', route('home'), data: ['payload']);
$http->json('GET', route('home', 'some arg'), ['payload']);
$http->json('GET', '/', ['data'], ['headers'], 1);
$http->json('GET', '/', ['data'], ['headers']);
$http->json('GET', '/', ['data']);
$http->json('GET', route('home'), headers: ['payload']);
$http->json('GET', route('home'), options: 1); 
```

Fix JSON GET calls with the route helper

---

README.md
composer.json
config/sets/laravel-collection.php
docs/rector_rules_overview.md
src/Rector/MethodCall/AvoidNegatedCollectionFilterOrRejectRector.php
src/Set/LaravelSetList.php
stubs/Illuminate/Support/Collection.php
stubs/Illuminate/Support/Enumerable.php
tests/Rector/MethodCall/AvoidNegatedCollectionFilterOrRejectRector/AvoidNegatedCollectionFilterOrRejectRectorTest.php
tests/Rector/MethodCall/AvoidNegatedCollectionFilterOrRejectRector/Fixture/fixture_cast.php.inc
tests/Rector/MethodCall/AvoidNegatedCollectionFilterOrRejectRector/Fixture/fixture_return_type.php.inc
tests/Rector/MethodCall/AvoidNegatedCollectionFilterOrRejectRector/Fixture/fixture_simple_negation.php.inc
tests/Rector/MethodCall/AvoidNegatedCollectionFilterOrRejectRector/config/configured_rule.php

The test currently fails and I am not sure how to make it work.
```diff
(new Collection([0, 1, null, -1]))
->reject(fn (?int $number): bool => is_null($number))
-    ->filter(fn (int $number): bool => $number > 0);
+    ->reject(fn (int $number): bool => ! ($number > 0));
```
I think there can be additional logic to simplify conditionals that use negated comparisons:
```diff
- ->filter(fn (int $n): bool => $n !== 0)
+ ->reject(fn (int $n): bool => $n === 0)
```
I also wonder where this rule would be included, perhaps in the code quality set list?
What do you think about this idea in general? Would you be up for inclusion?

Add AvoidNegatedCollectionFilterOrRejectRector

---

README.md

https://github.com/driftingly/rector-laravel/pull/234#discussion_r1697277741

Improve documentation about sets

---

config/sets/laravel80.php
config/sets/laravel90.php
stubs/Illuminate/Container/Container.php
stubs/Illuminate/Contracts/Container/Container.php
stubs/Illuminate/Contracts/Foundation/Application.php
stubs/Illuminate/Database/Eloquent/Model.php
stubs/Illuminate/Foundation/Application.php
stubs/Illuminate/Queue/Failed/FailedJobProviderInterface.php
tests/Sets/Laravel90/Fixture/application_class_lang_path_new_attribute.php.inc.php.inc
tests/Sets/Laravel90/Fixture/application_class_storage_path_new_attribute.php.inc.php.inc
tests/Sets/Laravel90/Fixture/application_lang_path_new_attribute.php.inc
tests/Sets/Laravel90/Fixture/application_storage_path_new_attribute.php.inc
tests/Sets/Laravel90/Fixture/exceptions_handler_ignore_with_public_visibility.php.inc
tests/Sets/Laravel90/Fixture/failed_job_provider_interface_new_attribute.php.inc
tests/Sets/Laravel90/Fixture/method_renames.php.inc
tests/Sets/Laravel90/Fixture/model_touch_new_attribute.php.inc
tests/Sets/Laravel90/Source/Collection.php

Fixes https://github.com/driftingly/rector-laravel/issues/239.
- Fixes a TODO in Laravel 8 set. Apparently, it's the only time we need to use `ArgumentAdderWithoutDefaultValue`.
- Replaces `ArgumentAdderWithoutDefaultValue` with `ArgumentAdder` in Laravel 9 set, while setting the scope to only the `ClassMethod`. This satisfies both conditions of modifying the class extensions where appropriate (#239) and keeping method/static calls intact (https://github.com/driftingly/rector-laravel/issues/220).
- Removes the change for `FailedJobProviderInterface` entirely, since an argument rename is needed in that case, but we don't have a rule in core Rector to only rename arguments, yet. I've kept the old test and improved the stub for future changes.
- Adds missing stubs for Container and …

Fix Argument Adding rules in Laravel 9 set

---

composer.json
src/Rector/ClassMethod/AddArgumentDefaultValueRector.php
src/Rector/MethodCall/ValidationRuleArrayStringValueToArrayRector.php

see https://github.com/rectorphp/rector/issues/8820#issuecomment-2337955117
Fixes https://github.com/driftingly/rector-laravel/issues/246

Bump to Rector 1.2.5 and fix compatible of isObjectType() usage to use ClassLike instead of ClassMethod

---

src/Set/LaravelSetProvider.php

- Adds a Set Provider to the project
This is now the standard for Rector repositories. Having this Set Provider will make it easier to display them on [GetRector.com/](https://getrector.com/find-rule)

Adds a set provider class

---

src/Set/LaravelSetProvider.php
tests/Sets/LaravelSetProviderTest.php

- Fixes the duplicate entries for the LaravelSetProvider
- Adds a unit test to check if it's providing the sets correctly.
Picked up as a mistake from #248

Fixes duplicate entries and adds a test

---

config/sets/laravel110.php
docs/rector_rules_overview.md
src/Rector/MethodCall/AssertSeeToAssertSeeHtmlRector.php
tests/Rector/MethodCall/AssertSeeToAssertSeeHtmlRector/AssertSeeToAssertSeeHtmlRectorTest.php
tests/Rector/MethodCall/AssertSeeToAssertSeeHtmlRector/Fixture/fixture_with_html_escape_false.php.inc
tests/Rector/MethodCall/AssertSeeToAssertSeeHtmlRector/Fixture/skip_with_html_escape_true_or_missing.php.inc
tests/Rector/MethodCall/AssertSeeToAssertSeeHtmlRector/Fixture/skip_with_non_test_response.php.inc
tests/Rector/MethodCall/AssertSeeToAssertSeeHtmlRector/Fixture/skip_with_other_method_names.php.inc
tests/Rector/MethodCall/AssertSeeToAssertSeeHtmlRector/config/configured_rule.php

The new rule is available from Laravel 11 ([PR](https://github.com/laravel/framework/pull/52285))
- Adds AssertSeeToAssertSeeHtmlRector.
- The rule is set as part of the Laravel 11 set.
- Docs are updated.
The rule changes:
```diff
-$response->assertSee("<li>foo</li>", false);
+$response->assertSeeHtml("<li>foo</li>");
```
```diff
-$response->assertDontSee("<li>foo</li>", false);
+$response->assertDontSeeHtml("<li>foo</li>");
```
```diff
-$response->assertSeeInOrder(["<li>foo</li>", "<li>bar</li>"], false);
+$response->assertSeeHtmlInOrder(["<li>foo</li>", "<li>bar</li>"]);
```

Add new rule AssertSeeToAssertSeeHtmlRector

---

docs/rector_rules_overview.md
src/Rector/MethodCall/AssertStatusToAssertMethodRector.php
stubs/Illuminate/Http/Response.php
stubs/Symfony/Component/HttpFoundation/Response.php
tests/Rector/MethodCall/AssertStatusToAssertMethodRector/Fixture/fixture_with_illuminate_response_constants.php.inc

- Uses PHPStan to a better effect instead of looking at what constants might be used
- Corrects a previously incorrect test
- Adds stubs for Laravel and Symfony responses
- Simplify the docs a little for the rule
I wrote this rule over a year or so ago now and learnt a lot since then. This should now allow for any integer value PHPStan can detect. For example:
```diff
-$this->get('/')->assertStatus(400 + 4);
+$this->get('/')->assertNotFound();
```
Before this the rule would only detect specific constants or the scalar integer using only what the PHP Parser had found.

Improvements to the AssertStatusToAssertMethodRector

---

src/Rector/Class_/AnonymousMigrationsRector.php

Somehow the `AnonymousMigrationsRector` rule's tests started hanging.
This happens only from the latest release of [Rector 1.2.7](https://github.com/rectorphp/rector/releases/tag/1.2.7), but it might be because of other dependencies of Rector itself.

Fix rule AnonymousMigrationsRector

---

docs/rector_rules_overview.md
src/Rector/FuncCall/RemoveDumpDataDeadCodeRector.php
tests/Rector/FuncCall/RemoveDumpDataDeadCodeRector/config/configured_rule.php

This PR makes it possible to configure the `RemoveDumpDataDeadCodeRector` rule with an array of dump functions. `dd()` and `dump()` are removed by default if the rule isn't used with a configuration in order to keep the current behavior.

Make RemoveDumpDataDeadCodeRector rule configurable

---

config/sets/laravel53.php
tests/Sets/Laravel53/Fixture/fixture.php.inc
tests/Sets/Laravel53/Laravel53Test.php
tests/Sets/Laravel53/config/configured_rule.php

Fixes https://github.com/driftingly/rector-laravel/issues/254.
We currently only have one rule for the Laravel 5.3 version, this PR adds some more deprecation/migration rules for that version. There are still some more that can be added for 5.3, but they might require custom rules.

Add migration rules for Laravel 5.3

---

docs/rector_rules_overview.md
src/Rector/ArrayDimFetch/EnvVariableToEnvHelperRector.php
tests/Rector/ArrayDimFetch/EnvVariableToEnvHelperRector/EnvVariableToEnvHelperRectorTest.php
tests/Rector/ArrayDimFetch/EnvVariableToEnvHelperRector/Fixture/fixture.php.inc
tests/Rector/ArrayDimFetch/EnvVariableToEnvHelperRector/Fixture/skip_dim_fetch_without_dim.php.inc
tests/Rector/ArrayDimFetch/EnvVariableToEnvHelperRector/Fixture/skip_non_env_variable.php.inc
tests/Rector/ArrayDimFetch/EnvVariableToEnvHelperRector/config/configured_rule.php

- Adds the EnvVariableToEnvHelperRector rule
- Provides tests
- Updates Docs
Just a useful rule to help transition PHP use of `$_ENV` to use the dotenv system of Laravel.

Adds the EnvVariableToEnvHelperRector rule

---

docs/rector_rules_overview.md
src/Rector/ArrayDimFetch/RequestVariablesToRequestFacadeRector.php
tests/Rector/ArrayDimFetch/RequestVariablesToRequestFacadeRector/Fixture/fixture.php.inc
tests/Rector/ArrayDimFetch/RequestVariablesToRequestFacadeRector/Fixture/skip_complex_dim.php.inc
tests/Rector/ArrayDimFetch/RequestVariablesToRequestFacadeRector/Fixture/skip_non_matching_variables.php.inc
tests/Rector/ArrayDimFetch/RequestVariablesToRequestFacadeRector/RequestVariablesToRequestFacadeRectorTest.php
tests/Rector/ArrayDimFetch/RequestVariablesToRequestFacadeRector/config/configured_rule.php

- Adds RequestVariablesToRequestFacadeRector rule
- Adds tests
- Updates Docs
Provides a nice transition from vanilla PHP to Laravel code.
```diff
-$_GET['value'];
-$_POST['value'];
-$_GET['value']['sub_value'];
+\Illuminate\Support\Facades\Request::input('value');
+\Illuminate\Support\Facades\Request::input('value');
+\Illuminate\Support\Facades\Request::input('value.sub_value');
```

Adds RequestVariablesToRequestFacadeRector rule

---

docs/rector_rules_overview.md
phpstan.neon
src/Rector/ClassMethod/AddGenericReturnTypeToRelationsRector.php
tests/Rector/ClassMethod/AddGenericReturnTypeToRelationsRector/AddGenericReturnTypeToRelationsRectorNewGenericsTest.php
tests/Rector/ClassMethod/AddGenericReturnTypeToRelationsRector/Source/NewApplication.php
tests/Rector/ClassMethod/AddGenericReturnTypeToRelationsRector/Source/OldApplication.php
tests/Rector/ClassMethod/AddGenericReturnTypeToRelationsRector/config/use_new_generics_configured_rule.php
tests/Rector/ClassMethod/AddGenericReturnTypeToRelationsRector/config/use_old_generics_configured_rule.php

Relates to https://github.com/driftingly/rector-laravel/pull/263.
- Makes the rule as non-configurable, as before, so users won't need to change their configurations.
- The check for the Laravel version is done within the rule, using Reflection, and checking the `VERSION` const of the Laravel `Application` class. Should we refactor this functionality into a class of its own, or wait for when we reach for it on future rules?
- I've used the Laravel Container's when-needs-give capabilities to provide an optional `Application` class for testing the two versions.
- I'm not sure if there is any performance penalty for doing that check on every model relationship. I don't think there is any significant penalty, but it's still something to remember.
Is there a better way to do this @peterfox?

Laravel 11 new generic types

---

config/sets/laravel90.php

There is a rule for converting model Attributes, but it is not applied in the corresponding set.
According to the documentation, this approach has been used since Laravel 9

Add MigrateToSimplifiedAttributeRector to Laravel 9 set

---

docs/rector_rules_overview.md
src/Rector/ArrayDimFetch/SessionVariableToSessionFacadeRector.php
tests/Rector/ArrayDimFetch/SessionVariableToSessionFacadeRector/Fixture/fixture.php.inc
tests/Rector/ArrayDimFetch/SessionVariableToSessionFacadeRector/Fixture/skip_dim_fetch_without_dim.php.inc
tests/Rector/ArrayDimFetch/SessionVariableToSessionFacadeRector/Fixture/skip_non_env_variable.php.inc
tests/Rector/ArrayDimFetch/SessionVariableToSessionFacadeRector/Fixture/skip_non_session_functions.php.inc
tests/Rector/ArrayDimFetch/SessionVariableToSessionFacadeRector/Fixture/skip_non_session_variable.php.inc
tests/Rector/ArrayDimFetch/SessionVariableToSessionFacadeRector/SessionVariableToSessionFacadeRectorTest.php
tests/Rector/ArrayDimFetch/SessionVariableToSessionFacadeRector/config/configured_rule.php

- Adds a new rule that converts Session variable and some of the Session functions to use the Laravel Session facade.
- Adds a test to cover these calls
This will make it easier to convert vanilla PHP applications to Laravel.
```diff
-$_SESSION['key'];
-$_SESSION['key'] = 'value';
-$_SESSION;
-session_regenerate_id();
-session_unset();
-session_destroy();
-session_start();
-unset($_SESSION['key']);
-isset($_SESSION['key'])
+\Illuminate\Support\Facades\Session::get('key');
+\Illuminate\Support\Facades\Session::put('key', 'value');
+\Illuminate\Support\Facades\Session::all();
+\Illuminate\Support\Facades\Session::regenerate();
+\Illuminate\Support\Facades\Session::flush();
+\Illuminate\Support\Facades\Session::destroy();
+\Illuminate\Support\Facades\Session::start(); …
```

Session variable to Session Facade

---

docs/rector_rules_overview.md
src/Rector/ArrayDimFetch/RequestVariablesToRequestFacadeRector.php
src/ValueObject/ReplaceRequestKeyAndMethodValue.php
tests/Rector/ArrayDimFetch/RequestVariablesToRequestFacadeRector/Fixture/fixture.php.inc

- Improves some of the scenarios with the `RequestVariablesToRequestFacadeRector` rule. Namely it handles the split between get, post and request into the right method calls. Also handles replacing the whole variable.
- Adds tests for the scenario
- Docs update
It makes this rule far more useful as a better 1:1 conversion of PHP to Laravel method calls on the Request facade.
```diff
-$_GET['value'];
-$_POST['value'];
-$_REQUEST['value'];
-$_POST;
-$_GET;
-$_REQUEST;
+\Illuminate\Support\Facades\Request::query('value');
+\Illuminate\Support\Facades\Request::post('value');
+\Illuminate\Support\Facades\Request::input('value');
+\Illuminate\Support\Facades\Request::query();
+\Illuminate\Support\Facades\Request::post();
+\Illuminate\Support\Facades\Request::all();
```

Improve request input refactor

---

docs/rector_rules_overview.md
src/Rector/ArrayDimFetch/ServerVariableToRequestFacadeRector.php
tests/Rector/ArrayDimFetch/ServerVariableToRequestFacadeRector/Fixture/fixture.php.inc
tests/Rector/ArrayDimFetch/ServerVariableToRequestFacadeRector/Fixture/skip_dim_fetch_without_dim.php.inc
tests/Rector/ArrayDimFetch/ServerVariableToRequestFacadeRector/Fixture/skip_non_server_variable.php.inc
tests/Rector/ArrayDimFetch/ServerVariableToRequestFacadeRector/ServerVariableToRequestFacadeRectorTest.php
tests/Rector/ArrayDimFetch/ServerVariableToRequestFacadeRector/config/configured_rule.php

- new ServerVariableToRequestFacadeRector rule
- adds tests
- updates docs
This converts a simple use of the `$_SERVER` PHP variable to use the Request facade.
```diff
-$_SERVER['VARIABLE'];
+\Illuminate\Support\Facade\Request::server('VARIABLE');
```

Adds ServerVariableToRequestFacadeRector rule

---

tests/Rector/FuncCall/ArgumentFuncCallToMethodCallRector/Fixture/auth.php.inc
tests/Rector/FuncCall/ArgumentFuncCallToMethodCallRector/Fixture/back.php.inc
tests/Rector/FuncCall/ArgumentFuncCallToMethodCallRector/Fixture/broadcast.php.inc
tests/Rector/FuncCall/ArgumentFuncCallToMethodCallRector/Fixture/config.php.inc
tests/Rector/FuncCall/ArgumentFuncCallToMethodCallRector/Fixture/route.php.inc
tests/Rector/FuncCall/ArgumentFuncCallToMethodCallRector/Fixture/session.php.inc
tests/Rector/FuncCall/ArgumentFuncCallToMethodCallRector/Fixture/view.php.inc

- updates tests for ArgumentFuncCallToMethodCallRector where the constructor is using readonly properties
Without this, tests break when using the latest version of Rector.
I'm unsure why this has cropped up and what method call is the cause of this. It makes sense in the code examples to be readonly but it's odd that's just happened like this.

Updates tests for ArgumentFuncCallToMethodCallRector

---

.github/workflows/downgraded_release.yaml
src/Rector/MethodCall/EloquentWhereRelationTypeHintingParameterRector.php
src/Rector/MethodCall/EloquentWhereTypeHintClosureParameterRector.php
stubs/Illuminate/Database/Eloquent/Model.php
tests/Rector/MethodCall/EloquentWhereRelationTypeHintingParameterRector/Fixture/fixture3.php.inc
tests/Rector/MethodCall/EloquentWhereRelationTypeHintingParameterRector/Fixture/skip_non_closure_argument.php.inc
tests/Rector/MethodCall/EloquentWhereRelationTypeHintingParameterRector/Fixture/skip_non_where_relation_method.php.inc
tests/Rector/MethodCall/EloquentWhereRelationTypeHintingParameterRector/Source/FooModel.php
tests/Rector/MethodCall/EloquentWhereTypeHintClosureParameterRector/Fixture/fixture2.php.inc
tests/Rector/MethodCall/EloquentWhereTypeHintClosureParameterRector/Fixture/skip_non_closure_argument.php.inc
tests/Rector/MethodCall/EloquentWhereTypeHintClosureParameterRector/Fixture/skip_non_where_method.php.inc
tests/Rector/MethodCall/EloquentWhereTypeHintClosureParameterRector/Source/FooModel.php

Related to #287 
- modifies two rules where a downgrade was causing the rule to break.
- adds additional tests.
- refactor the tests to not define classes in the fixtures and use source objects instead.
- sets up the build mechanism to retest code after a downgrade.
It looks like the `DowngradeMatchToSwitchRector` rule has an issue there which ended up removing code required to check the method causing the downgraded `EloquentWhereTypeHintClosureParameterRector` to break.
@driftingly @GeniJaho, we should be careful to make sure contributors add skip fixtures to cover conditions that ensure the rules they build don't affect code they're not meant to.

EloquentWhereTypeHintClosureParameterRector refactor

---

src/Rector/MethodCall/WhereToWhereLikeRector.php
stubs/Illuminate/Contracts/Database/Query/Expression.php
stubs/Illuminate/Database/Grammar.php
stubs/Illuminate/Support/Facades/DB.php
tests/Rector/MethodCall/WhereToWhereLikeRector/Fixture/Default/skip_with_expressions.php.inc
tests/Rector/MethodCall/WhereToWhereLikeRector/Fixture/Postgres/SkipWithExpressions.php.inc

Fixes https://github.com/driftingly/rector-laravel/pull/267#issuecomment-2586935995.

Do not convert to whereLike methods with Expressions

---

src/Set/LaravelSetProvider.php

Most of our rules do not appear on the [Find Rule](https://getrector.com/find-rule) page, because they're not [part of a set](https://github.com/rectorphp/getrector-com/pull/2800). And we don't have all the sets listed there.
- Adds two missing sets: `LARAVEL_COLLECTION` and `LARAVEL_ARRAYACCESS_TO_METHOD_CALL`.
- Replaces `ARRAY_STR_FUNCTIONS_TO_STATIC_CALL` with `LARAVEL_ARRAY_STR_FUNCTION_TO_STATIC_CALL`, since all our sets start with `Laravel`. We should probably deprecate the old name.
- Reworded some of the sets, and reordered them alphabetically. The custom sets will appear first, then the Livewire 3 set, and finally the Laravel Level sets from 11 to 5.

Update LaravelSetProvider with missing sets

---

src/Rector/Coalesce/ApplyDefaultInsteadOfNullCoalesceRector.php
tests/Rector/Coalesce/ApplyDefaultInsteadOfNullCoalesceRector/Fixture/skip_throw_exceptions.php.inc

Hi, It will fix the setting an exception as a default value bug as reported in #292.

Skip setting an exception as a default value in ApplyDefaultInsteadOfNullCoalesceRector

---

config/sets/laravel-container-string-to-fully-qualified-name.php

https://github.com/driftingly/rector-laravel/issues/293
The Migrator instance is not bound to the class name in the IoC container, it is bound to the migrator alias. I guess it should not be updated.
https://github.com/laravel/framework/blob/11.x/src/Illuminate/Database/MigrationServiceProvider.php#L80

chore: removed migrator from the list as not needed

---

composer.json
src/NodeFactory/ModelFactoryNodeFactory.php
src/Rector/ClassMethod/AddArgumentDefaultValueRector.php
src/Rector/ClassMethod/AddGenericReturnTypeToRelationsRector.php
src/Rector/ClassMethod/AddParentBootToModelClassMethodRector.php
src/Rector/ClassMethod/AddParentRegisterToEventServiceProviderRector.php
src/Rector/Class_/AddExtendsAnnotationToModelFactoriesRector.php
src/Rector/Class_/LivewireComponentComputedMethodToComputedAttributeRector.php
src/Rector/Class_/LivewireComponentQueryStringToUrlAttributeRector.php
src/Rector/FuncCall/FactoryFuncCallToStaticCallRector.php
src/Rector/FuncCall/TypeHintTappableCallRector.php
src/Rector/MethodCall/EloquentOrderByToLatestOrOldestRector.php
src/Rector/MethodCall/ReverseConditionableMethodCallRector.php
src/Rector/PropertyFetch/OptionalToNullsafeOperatorRector.php
src/Rector/StaticCall/EloquentMagicMethodToQueryBuilderRector.php
src/Rector/StaticCall/MinutesToSecondsInCacheRector.php
src/Rector/StaticCall/RouteActionCallableRector.php
src/Set/LaravelLevelSetList.php
src/Set/LaravelSetList.php
src/Set/LaravelSetProvider.php
src/Set/Packages/Cashier/CashierLevelSetList.php
src/Set/Packages/Cashier/CashierSetList.php
src/Set/Packages/Livewire/LivewireLevelSetList.php
src/Set/Packages/Livewire/LivewireSetList.php
tests/Sets/LaravelSetProviderTest.php

The dev-main installable from 8.2 platform, but code is 8.3 compatible,
see example code
https://github.com/driftingly/rector-laravel/blob/6b32c5faecc1fd0c2735e9acde9ae28e3bc1e56d/src/Rector/FuncCall/DispatchNonShouldQueueToDispatchSyncRector.php#L28-L34

Update composer.json to use php 8.3 requirement

---

config/sets/laravel120.php
config/sets/level/up-to-laravel-120.php
src/Rector/MethodCall/ContainerBindConcreteWithClosureOnlyRector.php
src/Set/LaravelLevelSetList.php
src/Set/LaravelSetList.php
src/Set/LaravelSetProvider.php
tests/Rector/MethodCall/ContainerBindConcreteWithClosureOnlyRector/ContainerBindConcreteWithClosureOnlyRectorTest.php
tests/Rector/MethodCall/ContainerBindConcreteWithClosureOnlyRector/Fixture/fixture.php.inc
tests/Rector/MethodCall/ContainerBindConcreteWithClosureOnlyRector/Source/SomeClass.php
tests/Rector/MethodCall/ContainerBindConcreteWithClosureOnlyRector/Source/SomeInterface.php
tests/Rector/MethodCall/ContainerBindConcreteWithClosureOnlyRector/config/configured_rule.php

- Adds the Laravel 12 set
- Adds a ContainerBindConcreteWithClosureOnlyRector rule
- Adds sets for the rule
Handles upgrades for this PR in Laravel https://github.com/laravel/framework/pull/54628
```diff
-$this->app->bind(SomeInterface::class, function () {
+$this->app->bind(function (): SomeInterface {
return new SomeClass();
});

Laravel 12 set with Bind Closures without Abstract rule

---

docs/rector_rules_overview.md
src/Rector/MethodCall/UnaliasCollectionMethodsRector.php
stubs/Illuminate/Support/Enumerable.php
tests/Rector/MethodCall/UnaliasCollectionMethodsRector/Fixture/fixture.php.inc

Add new aliases to `UnaliasCollectionMethodsRector` added in #291

Add new alias to `UnaliasCollectionMethods`

---

src/Rector/MethodCall/EloquentOrderByToLatestOrOldestRector.php
tests/Rector/MethodCall/EloquentOrderByToLatestOrOldestRector/Fixture/skip_if_direction_arg_is_not_string.php.inc

Fixes https://github.com/driftingly/rector-laravel/issues/302.
When the direction argument is not a string we skip the refactoring entirely.

Skip refactoring on EloquentOrderByToLatestOrOldestRector

---

commands/MakeRuleCommand.php
commands/make-rule.php
composer.json
duster.json
templates/new-rule/src/Rector/__NAME__.php
templates/new-rule/tests/Rector/__NAME__/Fixture/some_class.php.inc
templates/new-rule/tests/Rector/__NAME__/__NAME__Test.php
templates/new-rule/tests/Rector/__NAME__/config/configured_rule.php

It's very difficult to add new rules to the repository, every time you have to copy an existing one and change everything.
I think we should implement a way to generate the base scaffolding needed for writing a new rule.
Modifying the `CustomRuleCommand` in the core Rector repository would make it unnecessarily complicated (https://github.com/rectorphp/rector-src/pull/6676).
- Ported an implementation of the original command without all the options and dependencies. The reason is I couldn't make `RectorConfig` run user-defined commands. I think they need to be configured in the core Rector implementation somehow.
- Added a new directory called `Commands`, registered in `autoload-dev` so it doesn't make it to the users' vendor.
- Added a new composer script to make it easy to run the …

Add a command to generate new rules

---

docs/rector_rules_overview.md
src/NodeAnalyzer/ExpectedClassMethodAnalyzer.php
src/NodeFactory/DispatchableTestsMethodsFactory.php
src/Rector/Class_/ReplaceExpectsMethodsInTestsRector.php
src/ValueObject/ExpectedClassMethodMethodCalls.php
tests/Rector/Class_/ReplaceExpectsMethodsInTestsRector/Fixture/fixture.php.inc

* refactors the ReplaceExpectsMethodsInTestsRector rule to handle more scenarios
* adds new tests
* Adds new ExpectedClassMethodMethodCalls value object
* Adds new DispatchableTestsMethodsFactory node factory
* Adds new ExpectedClassMethodAnalyzer analyser
The original version while working was a bit basic and only covered `expectsJobs` and `expectsEvents`. It never found any uses of `doesntExpectJobs` and `doesntExpectEvents` because it just felt too complex to make happen within a single rule.
The rule now handles it nicely.
```diff
use Illuminate\Foundation\Testing\TestCase;
class SomethingTest extends TestCase
{
public function testSomething()
{
-        $this->expectsJobs([\App\Jobs\SomeJob::class, \App\Jobs\SomeOtherJob::class]);
- …
```

Fixup expected jobs and events rule

---

config/sets/laravel120.php
docs/rector_rules_overview.md
src/Rector/ClassMethod/ScopeNamedClassMethodToScopeAttributedClassMethodRector.php
tests/Rector/ClassMethod/ScopeNamedClassMethodToScopeAttributedClassMethodRector/Fixture/fixture.php.inc
tests/Rector/ClassMethod/ScopeNamedClassMethodToScopeAttributedClassMethodRector/Fixture/non_duplicate_nodes.php.inc
tests/Rector/ClassMethod/ScopeNamedClassMethodToScopeAttributedClassMethodRector/Fixture/non_matching_methods.php.inc
tests/Rector/ClassMethod/ScopeNamedClassMethodToScopeAttributedClassMethodRector/Fixture/non_method_duplicate.php.inc
tests/Rector/ClassMethod/ScopeNamedClassMethodToScopeAttributedClassMethodRector/Fixture/non_model_class.php.inc
tests/Rector/ClassMethod/ScopeNamedClassMethodToScopeAttributedClassMethodRector/ScopeNamedClassMethodToScopeAttributedClassMethodRectorTest.php
tests/Rector/ClassMethod/ScopeNamedClassMethodToScopeAttributedClassMethodRector/config/configured_rule.php

* creates the new rule and adds it to the Laravel 12 set.
* adds tests
* updates docs
Added in Laravel 12 https://github.com/laravel/framework/pull/54450
```diff
class User extends Model
{
-    public function scopeActive($query)
+    #[\Illuminate\Database\Eloquent\Attributes\Scope]
+    public function active($query)
{
return $query->where('active', 1);
}
}
```

Scope to use attribute rule

---

docs/rector_rules_overview.md
src/NodeAnalyzer/FacadeAssertionAnalyzer.php
src/Rector/StaticCall/AssertWithClassStringToTypeHintedClosureRector.php
tests/Rector/StaticCall/AssertWithClassStringToTypeHintedClosureRector/AssertWithClassStringToTypeHintedClosureRectorTest.php
tests/Rector/StaticCall/AssertWithClassStringToTypeHintedClosureRector/Fixture/fixture.php.inc
tests/Rector/StaticCall/AssertWithClassStringToTypeHintedClosureRector/Fixture/skip_first_class_callable.php.inc
tests/Rector/StaticCall/AssertWithClassStringToTypeHintedClosureRector/Fixture/skip_missing_closure_param.php.inc
tests/Rector/StaticCall/AssertWithClassStringToTypeHintedClosureRector/Fixture/skip_non_closure_arg.php.inc
tests/Rector/StaticCall/AssertWithClassStringToTypeHintedClosureRector/Fixture/skip_non_existing_class.php.inc
tests/Rector/StaticCall/AssertWithClassStringToTypeHintedClosureRector/Fixture/skip_non_matching_static_method_call.php.inc
tests/Rector/StaticCall/AssertWithClassStringToTypeHintedClosureRector/Source/SomeClass.php
tests/Rector/StaticCall/AssertWithClassStringToTypeHintedClosureRector/config/configured_rule.php

* Adds `AssertWithClassStringToTypeHintedClosureRector` rule.
* Adds a `FacadeAssertionAnalyzer` class.
* Adds tests for the rule.
* Updates the docs.
Helps remove a redundant argument to the use of assertDispatched.
```diff
-Bus::assertDispatched(OrderCreated::class, function ($job) {
+Bus::assertDispatched(function (OrderCreated $job) {
return true;
});
```
This can probably be expanded further but I've left it as just Event and Bus assertDispatch calls.

Assert class to type hinted closure

---

config/sets/laravel-facade-aliases-to-full-names.php

Noticed that Context was missing so I went ahead and added it.

Add `Context` to facade-aliases-to-full-names

---

phpunit.xml
src/Rector/ClassMethod/MigrateToSimplifiedAttributeRector.php
src/Rector/Class_/AddExtendsAnnotationToModelFactoriesRector.php
src/Rector/Class_/ReplaceExpectsMethodsInTestsRector.php
src/Rector/MethodCall/EloquentOrderByToLatestOrOldestRector.php
src/Rector/MethodCall/UseComponentPropertyWithinCommandsRector.php

New warnings coming from core Rector because of a new check for unchanged nodes that are still returned from the `refactor()` method. This causes an unnecessary performance hit, however small.

Fix test warnings

---

docs/rector_rules_overview.md
src/Rector/ClassMethod/ScopeNamedClassMethodToScopeAttributedClassMethodRector.php
tests/Rector/ClassMethod/ScopeNamedClassMethodToScopeAttributedClassMethodRector/Fixture/fixture.php.inc
tests/Rector/ClassMethod/ScopeNamedClassMethodToScopeAttributedClassMethodRector/Fixture/non_duplicate_nodes.php.inc

- Changed access modifier from public to protected.
[Laravel Doc](https://laravel.com/docs/12.x/eloquent#local-scopes) suggests to use protected access modifier.
When I was upgrading my project,I noticed that if the scope had the public modifier then the scope wasn't working.
example error message
```php
// if I call like this
$post->published()->get();
ArgumentCountError: Too few arguments to function App\Models\Post::published(), 0 passed in /test-app/tests/Unit/PostTest.php on line 69 and exactly 1 expected
// if I call like this
Post::published()->get();
Error: Non-static method App\Models\Post::published() cannot be called statically
```
scope
```php
#[Scope]
public function published(Builder $query): void
{
$query->where('status', PostStatusEnum::PUBLISHED);
}
```

Change method visibility to protected for scope methods

---

docs/rector_rules_overview.md
src/Rector/ArrayDimFetch/RequestVariablesToRequestFacadeRector.php
tests/Rector/ArrayDimFetch/RequestVariablesToRequestFacadeRector/Fixture/fixture_isset.php.inc
tests/Rector/ArrayDimFetch/RequestVariablesToRequestFacadeRector/Fixture/skip_isset_dim.php.inc

- Add isset support to `RequestVariablesToRequestFacade`
I used this rule on my legacy code base and it broke things because isset can only handle variables. The rule for the session facade works with isset so I added it here as well.
When you look at this you'll see `isset($_REQUEST['a'])` uses `Request::exists('a')` while `$_POST` and `$_GET` use `Request::query('a') !== null` and `Request::post('a') !== null`. The request facade doesn't have a post exists method so I figured it would be better to have it null check.

Add isset to RequestVariablesToRequestFacade

---

src/Rector/MethodCall/ValidationRuleArrayStringValueToArrayRector.php
tests/Rector/MethodCall/ValidationRuleArrayStringValueToArrayRector/Fixture/applies_to_http_requests.php.inc

Fixes https://github.com/driftingly/rector-laravel/issues/326.

Make ValidationRuleArrayStringValueToArrayRector work with Request object calls

---

src/Set/LaravelSetProvider.php
tests/Sets/LaravelSetProviderTest.php

Fixes https://github.com/driftingly/rector-laravel/issues/343.
We generate the set names, but we were doing it in the wrong order :sweat_smile:.
This PR does not solve the issue of sets that show they contain some rules, but those rules don't show up if you select the set. It's the configured ones like `RenameClassRector`.
I'm not sure if that should be fixed in this repository or the [getrector-com](https://github.com/rectorphp/getrector-com) repository.

Fix set names in LaravelSetProvider

---

src/Rector/ClassMethod/AddGenericReturnTypeToRelationsRector.php
tests/Rector/ClassMethod/AddGenericReturnTypeToRelationsRector/Fixture/NewGenerics/skip-already-set-generic.php.inc

- AddGenericReturnTypeToRelationsRector updates
- additional test scenario for AddGenericReturnTypeToRelationsRector
Reported by @brunogaspar  that the rule was working okay but would overwrite tags with a fully qualified name even when the tag was already correct.
This PR seeks to change the situation so if the tag exists, then it will not apply any changes.
Looking at this rule. There's a few changes that might be required when it comes to the pivot changes that were added in #316. I have a feeling relationships like MorphToMany haven't been considered and it should probably assign the Pivot class if the relationship uses one.

Stop overriding previous tags

---

docs/rector_rules_overview.md
src/NodeAnalyzer/CallUserFuncAnalyzer.php
src/Rector/Class_/UseForwardCallsTraitRector.php
src/ValueObject/ForwardingCall.php
tests/Rector/Class_/UseForwardCallsTraitRector/Fixture/dont_duplicate_trait.php.inc
tests/Rector/Class_/UseForwardCallsTraitRector/Fixture/fixture.php.inc
tests/Rector/Class_/UseForwardCallsTraitRector/Fixture/skip_complex_func_call.php.inc
tests/Rector/Class_/UseForwardCallsTraitRector/Fixture/skip_first_class_callable_use.php.inc
tests/Rector/Class_/UseForwardCallsTraitRector/Fixture/works_with_first_class_callable_callable.php.inc
tests/Rector/Class_/UseForwardCallsTraitRector/UseForwardCallsTraitRectorTest.php
tests/Rector/Class_/UseForwardCallsTraitRector/config/configured_rule.php

- Adds a new `UseForwardCallsTraitRector` to the repo
- Adds a new analyzer and value object to keep the rule a bit smaller
I've found in a few projects where having the forward calls trait would lead to better debugging.
```diff
class SomeClass
{
+    use ForwardCalls;
public function __call($method, $parameters)
{
-        return call_user_func_array([$this->foo, $method], $parameters);
+        return $this->forwardCallTo($this->foo, $method, $parameters);
}
}
```

Rule to use Forward calls trait

---

src/Set/LaravelSetProvider.php
tests/Sets/LaravelSetProviderTest.php

Hello!
Please see https://github.com/rectorphp/rector-src/pull/7110 and https://getrector.com/documentation/custom-set-provider#content-2-add-your-composertriggeredset-objects-to-the-provide-method for reference
These changes (with the PR mentioned above) will allow users to simply specify the following in their rector config and automatically have all the rectors up to the package version applied:
```php
->withComposerBased(laravel: true)
```
Thanks!

feat: add composer-triggered set for version sets

---

src/Rector/PropertyFetch/ReplaceFakerInstanceWithHelperRector.php
tests/Rector/PropertyFetch/ReplaceFakerInstanceWithHelperRector/Fixture/interpolated_strings.php.inc

Hello!
This closes #357 by adding support for interpolated strings to the `ReplaceFakerInstanceWithHelperRector`. PHP does not support function calls inside of strings.
Thanks!

fix: add interpolated strings support to ReplaceFakerInstanceWithHelperRector

---

composer.json
config/sets/laravel-collection.php
src/Rector/MethodCall/ConvertEnumerableToArrayToAllRector.php
stubs/Illuminate/Contracts/Support/Arrayable.php
stubs/Illuminate/Support/Enumerable.php
tests/Rector/MethodCall/ConvertEnumerableToArrayToAllRector/ConvertEnumerableToArrayToAllRectorTest.php
tests/Rector/MethodCall/ConvertEnumerableToArrayToAllRector/Fixture/fixture.php.inc
tests/Rector/MethodCall/ConvertEnumerableToArrayToAllRector/Fixture/skip_arrayble.php.inc
tests/Rector/MethodCall/ConvertEnumerableToArrayToAllRector/Fixture/skip_arrayble_union.php.inc
tests/Rector/MethodCall/ConvertEnumerableToArrayToAllRector/Fixture/skip_mixed.php.inc
tests/Rector/MethodCall/ConvertEnumerableToArrayToAllRector/config/configured_rule.php
tests/debug_functions.php

Hello!
This is a companion PR to https://github.com/larastan/larastan/pull/2311
The `toArray()` method on an Enumerable maps over all the items and recursively calls the `toArray()` method on each item if it is an Arrayable object. For collections that do not contain any Arrayable items, this is an unnecessary map operation and the method can be replaced with `all()` which simply returns the underlying array.
I also added the upstream `d` and `dd` functions to help when writing tests since those did not exist because they are rector dev dependencies.
Thanks!

feat: add ConvertEnumerableToArrayToAllRector

---

docs/rector_rules_overview.md
src/Rector/Class_/UseForwardsCallsTraitRector.php
tests/Rector/Class_/UseForwardsCallsTraitRector/Fixture/dont_duplicate_trait.php.inc
tests/Rector/Class_/UseForwardsCallsTraitRector/Fixture/fixture.php.inc
tests/Rector/Class_/UseForwardsCallsTraitRector/Fixture/skip_complex_func_call.php.inc
tests/Rector/Class_/UseForwardsCallsTraitRector/Fixture/skip_first_class_callable_use.php.inc
tests/Rector/Class_/UseForwardsCallsTraitRector/Fixture/works_with_first_class_callable_callable.php.inc
tests/Rector/Class_/UseForwardsCallsTraitRector/UseForwardsCallsTraitRectorTest.php
tests/Rector/Class_/UseForwardsCallsTraitRector/config/configured_rule.php

> Correct `ForwardCalls` to `ForwardsCalls`.
* [https://github.com/laravel/framework/blob/12.x/src/Illuminate/Support/Traits/ForwardsCalls.php#L8C7-L8C20](https://github.com/laravel/framework/blob/12.x/src/Illuminate/Support/Traits/ForwardsCalls.php#L8C7-L8C20)
* [https://github.com/driftingly/rector-laravel/blob/main/src/Rector/Class_/UseForwardCallsTraitRector.php#L27C75-L27C87](https://github.com/driftingly/rector-laravel/blob/main/src/Rector/Class_/UseForwardCallsTraitRector.php#L27C75-L27C87)
* [Tests](https://github.com/guanguans/rector-laravel/actions/runs/16898445203)
* [Code Analysis](https://github.com/guanguans/rector-laravel/actions/runs/16898445208)

Fix `UseForwardCallsTraitRector`

---

composer.json
config/sets/laravel-code-quality.php
src/Rector/Expr/AppEnvironmentComparisonToParameterRector.php
tests/Rector/Expr/AppEnvironmentComparisonToParameterRector/Fixture/fixture.php.inc
tests/Rector/Expr/AppEnvironmentComparisonToParameterRector/Fixture/in_array.php.inc

Hello!
This adds several improvements:
- support for the `in_array` function
- support for `!=` and `!==` operators
- support for the cleaner `isLocal` and `isProduction` methods
I also saw that this rule was not in any set, so I created a code style set (similar to the upstream rector one) for this and others (I figured this was more stylistic than code quality)
Thanks!

feat: improve AppEnvironmentComparisonToParameterRector

---

README.md

Hello!
This updates the readme with the new configure instructions now that the package support composer based sets
Thanks!

docs: update docs for version auto-detection

---

composer.json
config/sets/laravel-arrayaccess-to-method-call.php
stubs/Illuminate/Cache/Repository.php
stubs/Illuminate/Config/Repository.php
stubs/Illuminate/Container/Container.php
stubs/Illuminate/Contracts/Cache/Repository.php
stubs/Illuminate/Contracts/Config/Repository.php
stubs/Illuminate/Contracts/Container/Container.php
stubs/Illuminate/Contracts/Foundation/Application.php
tests/Sets/ArrayAccessToMethodCall/Fixture/fixture.php.inc

Hello!
This adds support for the exists, set, and unset operations that can happen on an ArrayAccess object.
This also adds the Cache contract to the list and cleans up the implementations---they are not needed since the contracts are listed and they all implement the contracts.
Thanks!

feat: add additional methods to laravel-arrayaccess-to-method-call

---

src/Rector/MethodCall/ContainerBindConcreteWithClosureOnlyRector.php
tests/Rector/MethodCall/ContainerBindConcreteWithClosureOnlyRector/Fixture/fixture.php.inc

Hi,
This is a proposed solution to solve the following issue when using `LARAVEL_120` set (`ContainerBindConcreteWithClosureOnlyRector` Rule):
The following piece of code
```php
foreach ([SomeClass::class, SomeOtherClass::class] as $item) {
$app->singleton($item, function () use ($item) {
return new $item();
});
}
```
Currently gets updated wrongly into
```php
foreach ([SomeClass::class, SomeOtherClass::class] as $item) {
$app->singleton($item, function () use ($item): SomeClass::class|SomeOtherClass::class {
return new $item();
});
}
```
[EDIT: The above is a made-up example to explain simply the issue, see my comment bellow]
I believe we should prevent any modification when the first argument is a variable. The above code should remain unchanged.
This PR is a proposed approach to do …

fix: ContainerBindConcreteWithClosureOnlyRector Rule when the abstract is a variable

---

src/Rector/ClassMethod/MakeModelAttributesAndScopesProtectedRector.php
tests/Rector/ClassMethod/MakeModelAttributesAndScopesProtectedRector/Fixture/skip-child-class.php.inc
tests/Rector/ClassMethod/MakeModelAttributesAndScopesProtectedRector/Source/ParentUser.php

This PR skips the `MakeModelAttributesAndScopesProtectedRectorTest` if the method is overriding a public parent method. Narrowing down the type in a child class results in a fatal error.

fix: skip rule when its overriding the method

---

src/Rector/Coalesce/ApplyDefaultInsteadOfNullCoalesceRector.php
tests/Rector/Coalesce/ApplyDefaultInsteadOfNullCoalesceRector/Fixture/fixture.php.inc
tests/Rector/Coalesce/ApplyDefaultInsteadOfNullCoalesceRector/Fixture/skip_request_input.php.inc

Fixes #385 and #308.
Unfortunately, I don't see a solution other than just excluding the Request object from this change, due to the its internal implementation of the `input` method.

Exclude `Request::input` calls from ApplyDefaultInsteadOfNullCoalesceRector

---

config/sets/laravel-code-quality.php
docs/rector_rules_overview.md
src/Rector/StaticCall/CarbonToDateFacadeRector.php
tests/Rector/StaticCall/CarbonToDateFacadeRector/CarbonToDateFacadeRectorTest.php
tests/Rector/StaticCall/CarbonToDateFacadeRector/Fixture/carbon_carbon.php.inc
tests/Rector/StaticCall/CarbonToDateFacadeRector/Fixture/illuminate_support_carbon.php.inc
tests/Rector/StaticCall/CarbonToDateFacadeRector/Fixture/skip_already_using_date_facade.php.inc
tests/Rector/StaticCall/CarbonToDateFacadeRector/Fixture/skip_non_carbon_class.php.inc
tests/Rector/StaticCall/CarbonToDateFacadeRector/Fixture/with_fully_qualified_names.php.inc
tests/Rector/StaticCall/CarbonToDateFacadeRector/config/configured_rule.php

Laravel's Date facade has some benefits; notably that it adheres to whatever handler is configured (so if you call `Date::use(CarbonImmutable::class)` in a service provider, all your dates will be immutable).
```diff
- Carbon::now();
+ Date::now();
```

Refactor Carbon static calls to Date Facade
