driftingly/rector-laravel

config/config.php
src/Rector/Assign/CallOnAppArrayAccessToStandaloneAssignRector.php
src/Rector/ClassMethod/AddParentBootToModelClassMethodRector.php
src/Rector/Class_/AddMockConsoleOutputFalseToConsoleTestsRector.php
src/Rector/Class_/PropertyDeferToDeferrableProviderToRector.php
src/Rector/MethodCall/ChangeQueryWhereDateValueWithCarbonRector.php
src/Rector/New_/AddGuardToLoginEventRector.php
src/Rector/New_/MakeTaggedPassedToParameterIterableTypeRector.php
src/Rector/StaticCall/Redirect301ToPermanentRedirectRector.php
src/Rector/StaticCall/RequestStaticValidateToInjectRector.php

[TASK] Add RenameClassNonPhpRector

---

composer.json

ref https://github.com/rectorphp/rector-src/pull/1359#discussion_r759953978

Update to latest rector-src dev-main

---

README.md

Since 8.x is the latest and recommended version

Suggest newer Laravel version

---

config/sets/laravel-static-to-injection.php

This PR closes #39 
I have fixed and tested it manually. it works fine.
I check the whole project there are no specific validations for the laravel rector sets. So I didn't add tests.

[BUG FIX]: Laravel static to injection

---

src/Rector/MethodCall/RedirectRouteToToRouteHelperRector.php
tests/Rector/MethodCall/RedirectRouteToToRouteHelperRector/Fixture/fixture.php.inc
tests/Rector/MethodCall/RedirectRouteToToRouteHelperRector/Fixture/skip_with_object_call.php.inc
tests/Rector/MethodCall/RedirectRouteToToRouteHelperRector/Fixture/skip_with_only_back.php.inc
tests/Rector/MethodCall/RedirectRouteToToRouteHelperRector/RedirectRouteToToRouteHelperRectorTest.php

I made too many mistakes on the last PR #45. So, This PR contains the fixes of it.

Code fixes of the redirect route rector class

---

src/Rector/Class_/AnonymousMigrationsRector.php
tests/Rector/Class_/AnonymousMigrationsRector/Fixture/skip_abstract_migration.php.inc

See https://github.com/rectorphp/rector-laravel/issues/50
Closes https://github.com/rectorphp/rector-laravel/issues/50

Skip abstract class when running AnonymousMigrationsRector

---

docs/rector_rules_overview.md
src/NodeAnalyzer/LumenRouteRegisteringMethodAnalyzer.php
src/Rector/MethodCall/LumenRoutesStringMiddlewareToArrayRector.php
tests/Rector/MethodCall/LumenRoutesStringMiddlewareToArrayRector/Fixture/group_method_middleware_not_an_array.php.inc
tests/Rector/MethodCall/LumenRoutesStringMiddlewareToArrayRector/Fixture/routes_method_middleware_not_an_array.php.inc
tests/Rector/MethodCall/LumenRoutesStringMiddlewareToArrayRector/Fixture/routes_method_middleware_string_array_notation.php.inc
tests/Rector/MethodCall/LumenRoutesStringMiddlewareToArrayRector/Fixture/skip_group_method_middleware_an_array.php.inc
tests/Rector/MethodCall/LumenRoutesStringMiddlewareToArrayRector/Fixture/skip_routes_method_middleware_an_array.php.inc
tests/Rector/MethodCall/LumenRoutesStringMiddlewareToArrayRector/LumenRoutesStringMiddlewareToArrayRectorTest.php
tests/Rector/MethodCall/LumenRoutesStringMiddlewareToArrayRector/config/configured_rule.php

Move from rectorphp/rector-src#2603

[Lumen] Create Lumen RoutesStringMiddlewareToArrayRector

---

src/Rector/StaticCall/RouteActionCallableRector.php
tests/Rector/StaticCall/RouteActionCallableRector/Fixture/fixture.php.inc
tests/Rector/StaticCall/RouteActionCallableRector/Fixture/named_route.php.inc

Closes https://github.com/rectorphp/rector-laravel/pull/60 
Fixes https://github.com/rectorphp/rector-laravel/issues/59

[Laravel] Add named route support on RouteActionCallableRector

---

.github/workflows/tests.yaml

This fixes some deprecation messages.

Update some workflow actions

---

docs/rector_rules_overview.md
src/Rector/FuncCall/NotFilledBlankFuncCallToBlankFilledFuncCallRector.php
tests/Rector/FuncCall/NotFilledBlankFuncCallToBlankFilledFuncCallRector/Fixture/fixture.php.inc
tests/Rector/FuncCall/NotFilledBlankFuncCallToBlankFilledFuncCallRector/NotFilledBlankFuncCallToBlankFilledFuncCallRectorTest.php
tests/Rector/FuncCall/NotFilledBlankFuncCallToBlankFilledFuncCallRector/config/configured_rule.php

* Adds the new rule
* Tests for the rule
* Documentation update
If you're using `!blank()`, then you might as well be using `filled()` and vice versa.

Change use of `!blank()` and `!filled()` to use the correct func

---

src/Rector/MethodCall/LumenRoutesStringMiddlewareToArrayRector.php

Remove usages of ArrayManipulator

Support Rector 0.17.11

---

config/sets/packages/cashier/cashier-13.php
config/sets/packages/cashier/cashier-14.php
src/Set/Packages/Cashier/CashierLevelSetList.php
src/Set/Packages/Cashier/CashierSetList.php

RE: PR #103
Looks like these paths weren't updated when the files were moved based on PR feedback

Correct paths

---

docs/rector_rules_overview.md

Some docs appear to be wrong since #173

[Fix] Docs regenerated

---

README.md
build/composer-php-72.json
composer.json
rector.php

This PR updates Rector to the recent `1.0` release 🥳

Update Rector to `1.0`

---

src/NodeFactory/RouterRegisterNodeAnalyzer.php
tests/Rector/StaticCall/RouteActionCallableRector/Fixture/using_route_alias.php.inc

Allow RouteActionCallableRector to work with \Route calls

---

README.md

Simply added badges for the Readme for Github and Packagist.

Github Badges

---

README.md

This PR updates the readme to add contributors.

Update readme to add contributors

---

src/NodeFactory/ModelFactoryNodeFactory.php
src/Rector/Namespace_/FactoryDefinitionRector.php
tests/Rector/Namespace_/FactoryDefinitionRector/Fixture/fixture_with_arrow_functions.php.inc

Fixes https://github.com/driftingly/rector-laravel/issues/212.

Fix FactoryDefinitionRector to work with arrow functions

---

src/Rector/Class_/ReplaceExpectsMethodsInTestsRector.php
src/Rector/Expr/AppEnvironmentComparisonToParameterRector.php
src/Rector/FuncCall/FactoryFuncCallToStaticCallRector.php
src/Rector/FuncCall/SleepFuncToSleepStaticCallRector.php
src/Rector/MethodCall/EloquentWhereRelationTypeHintingParameterRector.php
src/Rector/MethodCall/EloquentWhereTypeHintClosureParameterRector.php
src/Rector/MethodCall/RefactorBlueprintGeometryColumnsRector.php
src/Rector/MethodCall/ReplaceWithoutJobsEventsAndNotificationsWithFacadeFakeRector.php
src/Rector/StaticCall/EloquentMagicMethodToQueryBuilderRector.php
src/Rector/StaticCall/ReplaceAssertTimesSendWithAssertSentTimesRector.php

Just a run of Rector/Lint as it appears to currently be broken

Clean up via rector / linting

---

docs/rector_rules_overview.md
src/Rector/MethodCall/ReverseConditionableMethodCallRector.php
stubs/Illuminate/Support/Traits/Conditionable.php
tests/Rector/MethodCall/ReverseConditionableMethodCallRector/Fixture/fixture.php.inc
tests/Rector/MethodCall/ReverseConditionableMethodCallRector/Fixture/skip_non_conditionable_object.php.inc
tests/Rector/MethodCall/ReverseConditionableMethodCallRector/ReverseConditionableMethodCallRectorTest.php
tests/Rector/MethodCall/ReverseConditionableMethodCallRector/Source/ConditionableExample.php
tests/Rector/MethodCall/ReverseConditionableMethodCallRector/config/configured_rule.php

* adds ReverseCondiationableMethodCallRector
* adds tests
* updates the docs
* Adds to the code quality set
This is a nice little code quality type rule.
```diff
-$conditionable->when(!$condition, function () {});
+$conditionable->unless($condition function () {});
```
```diff
-$conditionable->unless(!$condition, function () {});
+$conditionable->when($condition, function () {});
```

Adds the ReverseCondiationableMethodCallRector

---

src/Rector/ClassMethod/AddGenericReturnTypeToRelationsRector.php
tests/Rector/ClassMethod/AddGenericReturnTypeToRelationsRector/Fixture/NewGenerics/relation-with-chained-method-calls.php.inc
tests/Rector/ClassMethod/AddGenericReturnTypeToRelationsRector/Fixture/OldGenerics/relation-with-chained-method-calls.php.inc

AddGenericReturnTypeToRelationsRector fix for chained relation call

---

docs/rector_rules_overview.md
src/Rector/MethodCall/ChangeQueryWhereDateValueWithCarbonRector.php

Fixes https://github.com/driftingly/rector-laravel/issues/309.

Update the rule definition for ChangeQueryWhereDateValueWithCarbonRector

---

docs/rector_rules_overview.md
src/Rector/Class_/AddMockConsoleOutputFalseToConsoleTestsRector.php

fix sample code in `src/Rector/Class_/AddMockConsoleOutputFalseToConsoleTestsRector.php`

fix sample code

---

.github/workflows/downgraded_release.yaml
build/composer-php-74.json
build/rector-downgrade-php-74.php

The build composer.json require rector 2,which require php 7.4

Downgrade to php 7.4 for release

---

src/Rector/StaticCall/DispatchToHelperFunctionsRector.php
tests/Rector/StaticCall/DispatchToHelperFunctionsRector/Fixture/skip_first_class_callable.php.inc

fix: skip first class callable in DispatchToHelperFunctionsRector

---

src/Rector/MethodCall/ValidationRuleArrayStringValueToArrayRector.php
tests/Rector/MethodCall/ValidationRuleArrayStringValueToArrayRector/Fixture/applies_to_http_requests.php.inc
tests/Rector/MethodCall/ValidationRuleArrayStringValueToArrayRector/Fixture/applies_to_string_interpolation.php.inc

Fix interpolation processing in ValidationRuleArrayStringValueToArrayRector
